/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createHackOManiaApiEndpointsParticipantsHackathonRegistrationQuestionsListResponseFromDiscriminatorValue, type HackOManiaApiEndpointsParticipantsHackathonRegistrationQuestionsListResponse } from '../../../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /participants/hackathons/{hackathonIdOrShortCode-id}/registration/questions
 */
export interface QuestionsRequestBuilder extends BaseRequestBuilder<QuestionsRequestBuilder> {
    /**
     * Get all registration questions for a hackathon, grouped by category, with the current user's submissions if any.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<HackOManiaApiEndpointsParticipantsHackathonRegistrationQuestionsListResponse>}
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<HackOManiaApiEndpointsParticipantsHackathonRegistrationQuestionsListResponse | undefined>;
    /**
     * Get all registration questions for a hackathon, grouped by category, with the current user's submissions if any.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const QuestionsRequestBuilderUriTemplate = "{+baseurl}/participants/hackathons/{hackathonIdOrShortCode%2Did}/registration/questions";
/**
 * Metadata for all the requests in the request builder.
 */
export const QuestionsRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: QuestionsRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "send",
        responseBodyFactory:  createHackOManiaApiEndpointsParticipantsHackathonRegistrationQuestionsListResponseFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
