/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createHackOManiaApiEndpointsOrganizersHackathonSubmissionsListResponseFromDiscriminatorValue, type HackOManiaApiEndpointsOrganizersHackathonSubmissionsListResponse } from '../../../../models/index.js';
// @ts-ignore
import { type WithSubmissionItemRequestBuilder, WithSubmissionItemRequestBuilderRequestsMetadata } from './item/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /organizers/hackathons/{id}/submissions
 */
export interface SubmissionsRequestBuilder extends BaseRequestBuilder<SubmissionsRequestBuilder> {
    /**
     * Gets an item from the ApiSdk.organizers.hackathons.item.submissions.item collection
     * @param submissionId Unique identifier of the item
     * @returns {WithSubmissionItemRequestBuilder}
     */
     bySubmissionId(submissionId: string) : WithSubmissionItemRequestBuilder;
    /**
     * Retrieves all submissions for a hackathon. Can filter by challenge or team. Requires organizer access.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<HackOManiaApiEndpointsOrganizersHackathonSubmissionsListResponse>}
     */
     get(requestConfiguration?: RequestConfiguration<SubmissionsRequestBuilderGetQueryParameters> | undefined) : Promise<HackOManiaApiEndpointsOrganizersHackathonSubmissionsListResponse | undefined>;
    /**
     * Retrieves all submissions for a hackathon. Can filter by challenge or team. Requires organizer access.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<SubmissionsRequestBuilderGetQueryParameters> | undefined) : RequestInformation;
}
/**
 * Retrieves all submissions for a hackathon. Can filter by challenge or team. Requires organizer access.
 */
export interface SubmissionsRequestBuilderGetQueryParameters {
    challengeId?: string;
    teamId?: string;
}
/**
 * Uri template for the request builder.
 */
export const SubmissionsRequestBuilderUriTemplate = "{+baseurl}/organizers/hackathons/{id}/submissions{?challengeId*,teamId*}";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const SubmissionsRequestBuilderNavigationMetadata: Record<Exclude<keyof SubmissionsRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    bySubmissionId: {
        requestsMetadata: WithSubmissionItemRequestBuilderRequestsMetadata,
        pathParametersMappings: ["submissionId"],
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const SubmissionsRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: SubmissionsRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "send",
        responseBodyFactory:  createHackOManiaApiEndpointsOrganizersHackathonSubmissionsListResponseFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
