/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createHackOManiaApiEndpointsOrganizersHackathonParticipantsBatchEmailResponseFromDiscriminatorValue, serializeHackOManiaApiEndpointsOrganizersHackathonParticipantsBatchEmailRequest, serializeHackOManiaApiEndpointsOrganizersHackathonParticipantsBatchEmailResponse, type HackOManiaApiEndpointsOrganizersHackathonParticipantsBatchEmailRequest, type HackOManiaApiEndpointsOrganizersHackathonParticipantsBatchEmailResponse } from '../../../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /organizers/hackathons/{hackathonId}/participants/batch-email
 */
export interface BatchEmailRequestBuilder extends BaseRequestBuilder<BatchEmailRequestBuilder> {
    /**
     * Send acceptance or rejection emails to multiple participants based on their review status.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<HackOManiaApiEndpointsOrganizersHackathonParticipantsBatchEmailResponse>}
     */
     post(body: HackOManiaApiEndpointsOrganizersHackathonParticipantsBatchEmailRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<HackOManiaApiEndpointsOrganizersHackathonParticipantsBatchEmailResponse | undefined>;
    /**
     * Send acceptance or rejection emails to multiple participants based on their review status.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: HackOManiaApiEndpointsOrganizersHackathonParticipantsBatchEmailRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const BatchEmailRequestBuilderUriTemplate = "{+baseurl}/organizers/hackathons/{hackathonId}/participants/batch-email";
/**
 * Metadata for all the requests in the request builder.
 */
export const BatchEmailRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: BatchEmailRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "send",
        responseBodyFactory:  createHackOManiaApiEndpointsOrganizersHackathonParticipantsBatchEmailResponseFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeHackOManiaApiEndpointsOrganizersHackathonParticipantsBatchEmailRequest,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
