/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { PurgeRequestBuilderRequestsMetadata, type PurgeRequestBuilder } from './purge/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /admin/cache
 */
export interface CacheRequestBuilder extends BaseRequestBuilder<CacheRequestBuilder> {
    /**
     * The purge property
     */
    get purge(): PurgeRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const CacheRequestBuilderUriTemplate = "{+baseurl}/admin/cache";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const CacheRequestBuilderNavigationMetadata: Record<Exclude<keyof CacheRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    purge: {
        requestsMetadata: PurgeRequestBuilderRequestsMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
