packages:
  - GeeksHackingPortal.WebApp
  - GeeksHackingPortal.WebSdk
  - GeeksHackingPortal.OidcWebPlayground

allowBuilds:
  '@firebase/util': true
  '@parcel/watcher': true
  es5-ext: true
  esbuild: true
  msw: true
  protobufjs: true
  sharp: true
  vue-demi: true

minimumReleaseAgeExclude:
  - '@kubb/ast@5.3.19'
  - '@kubb/cli@5.3.19'
  - '@kubb/core@5.3.19'

onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - sharp
  - unrs-resolver
  - vue-demi
