packages:
  - GeeksHackingPortal.WebApp
  - GeeksHackingPortal.WebSdk
  - GeeksHackingPortal.OidcWebPlayground

onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - sharp
  - unrs-resolver
  - vue-demi
