/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createHackOManiaApiEndpointsParticipantsHackathonTeamsCreateResponseFromDiscriminatorValue, serializeHackOManiaApiEndpointsParticipantsHackathonTeamsCreateRequest, serializeHackOManiaApiEndpointsParticipantsHackathonTeamsCreateResponse, type HackOManiaApiEndpointsParticipantsHackathonTeamsCreateRequest, type HackOManiaApiEndpointsParticipantsHackathonTeamsCreateResponse } from '../../../../models/index.js';
// @ts-ignore
import { type WithTeamItemRequestBuilder, WithTeamItemRequestBuilderNavigationMetadata, WithTeamItemRequestBuilderRequestsMetadata } from './item/index.js';
// @ts-ignore
import { LeaveRequestBuilderRequestsMetadata, type LeaveRequestBuilder } from './leave/index.js';
// @ts-ignore
import { MeRequestBuilderRequestsMetadata, type MeRequestBuilder } from './me/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /participants/hackathons/{hackathonIdOrShortCode-id}/teams
 */
export interface TeamsRequestBuilder extends BaseRequestBuilder<TeamsRequestBuilder> {
    /**
     * The leave property
     */
    get leave(): LeaveRequestBuilder;
    /**
     * The me property
     */
    get me(): MeRequestBuilder;
    /**
     * Gets an item from the ApiSdk.participants.hackathons.item.teams.item collection
     * @param teamId Unique identifier of the item
     * @returns {WithTeamItemRequestBuilder}
     */
     byTeamId(teamId: string) : WithTeamItemRequestBuilder;
    /**
     * Creates a new team for the hackathon and adds the current user as a member.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<HackOManiaApiEndpointsParticipantsHackathonTeamsCreateResponse>}
     */
     post(body: HackOManiaApiEndpointsParticipantsHackathonTeamsCreateRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<HackOManiaApiEndpointsParticipantsHackathonTeamsCreateResponse | undefined>;
    /**
     * Creates a new team for the hackathon and adds the current user as a member.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: HackOManiaApiEndpointsParticipantsHackathonTeamsCreateRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const TeamsRequestBuilderUriTemplate = "{+baseurl}/participants/hackathons/{hackathonIdOrShortCode%2Did}/teams";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const TeamsRequestBuilderNavigationMetadata: Record<Exclude<keyof TeamsRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byTeamId: {
        requestsMetadata: WithTeamItemRequestBuilderRequestsMetadata,
        navigationMetadata: WithTeamItemRequestBuilderNavigationMetadata,
        pathParametersMappings: ["teamId"],
    },
    leave: {
        requestsMetadata: LeaveRequestBuilderRequestsMetadata,
    },
    me: {
        requestsMetadata: MeRequestBuilderRequestsMetadata,
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const TeamsRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: TeamsRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "send",
        responseBodyFactory:  createHackOManiaApiEndpointsParticipantsHackathonTeamsCreateResponseFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeHackOManiaApiEndpointsParticipantsHackathonTeamsCreateRequest,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
