/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createHackOManiaApiEndpointsOrganizersHackathonChallengesCreateResponseFromDiscriminatorValue, createHackOManiaApiEndpointsOrganizersHackathonChallengesListResponseFromDiscriminatorValue, serializeHackOManiaApiEndpointsOrganizersHackathonChallengesCreateRequest, serializeHackOManiaApiEndpointsOrganizersHackathonChallengesCreateResponse, type HackOManiaApiEndpointsOrganizersHackathonChallengesCreateRequest, type HackOManiaApiEndpointsOrganizersHackathonChallengesCreateResponse, type HackOManiaApiEndpointsOrganizersHackathonChallengesListResponse } from '../../../../models/index.js';
// @ts-ignore
import { type WithChallengeItemRequestBuilder, WithChallengeItemRequestBuilderRequestsMetadata } from './item/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /organizers/hackathons/{id}/challenges
 */
export interface ChallengesRequestBuilder extends BaseRequestBuilder<ChallengesRequestBuilder> {
    /**
     * Gets an item from the ApiSdk.organizers.hackathons.item.challenges.item collection
     * @param challengeId Unique identifier of the item
     * @returns {WithChallengeItemRequestBuilder}
     */
     byChallengeId(challengeId: string) : WithChallengeItemRequestBuilder;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<HackOManiaApiEndpointsOrganizersHackathonChallengesListResponse>}
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<HackOManiaApiEndpointsOrganizersHackathonChallengesListResponse | undefined>;
    /**
     * Creates a new challenge for the hackathon. Requires organizer access.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<HackOManiaApiEndpointsOrganizersHackathonChallengesCreateResponse>}
     */
     post(body: HackOManiaApiEndpointsOrganizersHackathonChallengesCreateRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<HackOManiaApiEndpointsOrganizersHackathonChallengesCreateResponse | undefined>;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
    /**
     * Creates a new challenge for the hackathon. Requires organizer access.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: HackOManiaApiEndpointsOrganizersHackathonChallengesCreateRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const ChallengesRequestBuilderUriTemplate = "{+baseurl}/organizers/hackathons/{id}/challenges";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const ChallengesRequestBuilderNavigationMetadata: Record<Exclude<keyof ChallengesRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byChallengeId: {
        requestsMetadata: WithChallengeItemRequestBuilderRequestsMetadata,
        pathParametersMappings: ["challengeId"],
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const ChallengesRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: ChallengesRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "send",
        responseBodyFactory:  createHackOManiaApiEndpointsOrganizersHackathonChallengesListResponseFromDiscriminatorValue,
    },
    post: {
        uriTemplate: ChallengesRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "send",
        responseBodyFactory:  createHackOManiaApiEndpointsOrganizersHackathonChallengesCreateResponseFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeHackOManiaApiEndpointsOrganizersHackathonChallengesCreateRequest,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
