/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { RedemptionsRequestBuilderRequestsMetadata, type RedemptionsRequestBuilder } from './redemptions/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /participants/hackathons/{hackathonIdOrShortCode-id}/resources/{resourceId}
 */
export interface WithResourceItemRequestBuilder extends BaseRequestBuilder<WithResourceItemRequestBuilder> {
    /**
     * The redemptions property
     */
    get redemptions(): RedemptionsRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const WithResourceItemRequestBuilderUriTemplate = "{+baseurl}/participants/hackathons/{hackathonIdOrShortCode%2Did}/resources/{resourceId}";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const WithResourceItemRequestBuilderNavigationMetadata: Record<Exclude<keyof WithResourceItemRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    redemptions: {
        requestsMetadata: RedemptionsRequestBuilderRequestsMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
