/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createHackOManiaApiEndpointsOrganizersHackathonResourcesCreateResponseFromDiscriminatorValue, createHackOManiaApiEndpointsOrganizersHackathonResourcesListResponseFromDiscriminatorValue, serializeHackOManiaApiEndpointsOrganizersHackathonResourcesCreateRequest, serializeHackOManiaApiEndpointsOrganizersHackathonResourcesCreateResponse, type HackOManiaApiEndpointsOrganizersHackathonResourcesCreateRequest, type HackOManiaApiEndpointsOrganizersHackathonResourcesCreateResponse, type HackOManiaApiEndpointsOrganizersHackathonResourcesListResponse } from '../../../../models/index.js';
// @ts-ignore
import { type WithResourceItemRequestBuilder, WithResourceItemRequestBuilderRequestsMetadata } from './item/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /organizers/hackathons/{hackathonId}/resources
 */
export interface ResourcesRequestBuilder extends BaseRequestBuilder<ResourcesRequestBuilder> {
    /**
     * Gets an item from the ApiSdk.organizers.hackathons.item.resources.item collection
     * @param resourceId Unique identifier of the item
     * @returns {WithResourceItemRequestBuilder}
     */
     byResourceId(resourceId: string) : WithResourceItemRequestBuilder;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<HackOManiaApiEndpointsOrganizersHackathonResourcesListResponse>}
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<HackOManiaApiEndpointsOrganizersHackathonResourcesListResponse | undefined>;
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<HackOManiaApiEndpointsOrganizersHackathonResourcesCreateResponse>}
     */
     post(body: HackOManiaApiEndpointsOrganizersHackathonResourcesCreateRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<HackOManiaApiEndpointsOrganizersHackathonResourcesCreateResponse | undefined>;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: HackOManiaApiEndpointsOrganizersHackathonResourcesCreateRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const ResourcesRequestBuilderUriTemplate = "{+baseurl}/organizers/hackathons/{hackathonId}/resources";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const ResourcesRequestBuilderNavigationMetadata: Record<Exclude<keyof ResourcesRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byResourceId: {
        requestsMetadata: WithResourceItemRequestBuilderRequestsMetadata,
        pathParametersMappings: ["resourceId"],
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const ResourcesRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: ResourcesRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "send",
        responseBodyFactory:  createHackOManiaApiEndpointsOrganizersHackathonResourcesListResponseFromDiscriminatorValue,
    },
    post: {
        uriTemplate: ResourcesRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "send",
        responseBodyFactory:  createHackOManiaApiEndpointsOrganizersHackathonResourcesCreateResponseFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeHackOManiaApiEndpointsOrganizersHackathonResourcesCreateRequest,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
