/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createHackOManiaApiEndpointsOrganizersHackathonRegistrationQuestionsCreateResponseFromDiscriminatorValue, createHackOManiaApiEndpointsOrganizersHackathonRegistrationQuestionsListResponseFromDiscriminatorValue, serializeHackOManiaApiEndpointsOrganizersHackathonRegistrationQuestionsCreateRequest, serializeHackOManiaApiEndpointsOrganizersHackathonRegistrationQuestionsCreateResponse, type HackOManiaApiEndpointsOrganizersHackathonRegistrationQuestionsCreateRequest, type HackOManiaApiEndpointsOrganizersHackathonRegistrationQuestionsCreateResponse, type HackOManiaApiEndpointsOrganizersHackathonRegistrationQuestionsListResponse } from '../../../../../models/index.js';
// @ts-ignore
import { InitializeRequestBuilderRequestsMetadata, type InitializeRequestBuilder } from './initialize/index.js';
// @ts-ignore
import { type WithQuestionItemRequestBuilder, WithQuestionItemRequestBuilderRequestsMetadata } from './item/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /organizers/hackathons/{hackathonId}/registration/questions
 */
export interface QuestionsRequestBuilder extends BaseRequestBuilder<QuestionsRequestBuilder> {
    /**
     * The initialize property
     */
    get initialize(): InitializeRequestBuilder;
    /**
     * Gets an item from the ApiSdk.organizers.hackathons.item.registration.questions.item collection
     * @param questionId Unique identifier of the item
     * @returns {WithQuestionItemRequestBuilder}
     */
     byQuestionId(questionId: string) : WithQuestionItemRequestBuilder;
    /**
     * Get all registration questions for a hackathon with their options.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<HackOManiaApiEndpointsOrganizersHackathonRegistrationQuestionsListResponse>}
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<HackOManiaApiEndpointsOrganizersHackathonRegistrationQuestionsListResponse | undefined>;
    /**
     * Create a new registration question for participants to answer.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<HackOManiaApiEndpointsOrganizersHackathonRegistrationQuestionsCreateResponse>}
     */
     post(body: HackOManiaApiEndpointsOrganizersHackathonRegistrationQuestionsCreateRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<HackOManiaApiEndpointsOrganizersHackathonRegistrationQuestionsCreateResponse | undefined>;
    /**
     * Get all registration questions for a hackathon with their options.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
    /**
     * Create a new registration question for participants to answer.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: HackOManiaApiEndpointsOrganizersHackathonRegistrationQuestionsCreateRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const QuestionsRequestBuilderUriTemplate = "{+baseurl}/organizers/hackathons/{hackathonId}/registration/questions";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const QuestionsRequestBuilderNavigationMetadata: Record<Exclude<keyof QuestionsRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byQuestionId: {
        requestsMetadata: WithQuestionItemRequestBuilderRequestsMetadata,
        pathParametersMappings: ["questionId"],
    },
    initialize: {
        requestsMetadata: InitializeRequestBuilderRequestsMetadata,
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const QuestionsRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: QuestionsRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "send",
        responseBodyFactory:  createHackOManiaApiEndpointsOrganizersHackathonRegistrationQuestionsListResponseFromDiscriminatorValue,
    },
    post: {
        uriTemplate: QuestionsRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "send",
        responseBodyFactory:  createHackOManiaApiEndpointsOrganizersHackathonRegistrationQuestionsCreateResponseFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeHackOManiaApiEndpointsOrganizersHackathonRegistrationQuestionsCreateRequest,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
