/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createHackOManiaApiEndpointsOrganizersHackathonResourcesUpdateResponseFromDiscriminatorValue, serializeHackOManiaApiEndpointsOrganizersHackathonResourcesUpdateRequest, serializeHackOManiaApiEndpointsOrganizersHackathonResourcesUpdateResponse, type HackOManiaApiEndpointsOrganizersHackathonResourcesUpdateRequest, type HackOManiaApiEndpointsOrganizersHackathonResourcesUpdateResponse } from '../../../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /organizers/hackathons/{id}/resources/{resourceId}
 */
export interface WithResourceItemRequestBuilder extends BaseRequestBuilder<WithResourceItemRequestBuilder> {
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     */
     delete(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<void>;
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<HackOManiaApiEndpointsOrganizersHackathonResourcesUpdateResponse>}
     */
     patch(body: HackOManiaApiEndpointsOrganizersHackathonResourcesUpdateRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<HackOManiaApiEndpointsOrganizersHackathonResourcesUpdateResponse | undefined>;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toDeleteRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPatchRequestInformation(body: HackOManiaApiEndpointsOrganizersHackathonResourcesUpdateRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const WithResourceItemRequestBuilderUriTemplate = "{+baseurl}/organizers/hackathons/{id}/resources/{resourceId}";
/**
 * Metadata for all the requests in the request builder.
 */
export const WithResourceItemRequestBuilderRequestsMetadata: RequestsMetadata = {
    delete: {
        uriTemplate: WithResourceItemRequestBuilderUriTemplate,
        adapterMethodName: "sendNoResponseContent",
    },
    patch: {
        uriTemplate: WithResourceItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "send",
        responseBodyFactory:  createHackOManiaApiEndpointsOrganizersHackathonResourcesUpdateResponseFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeHackOManiaApiEndpointsOrganizersHackathonResourcesUpdateRequest,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
