/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { CheckOutRequestBuilderRequestsMetadata, type CheckOutRequestBuilder } from './checkOut/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /participants/hackathons/{hackathonIdOrShortCode-id}/venue
 */
export interface VenueRequestBuilder extends BaseRequestBuilder<VenueRequestBuilder> {
    /**
     * The checkOut property
     */
    get checkOut(): CheckOutRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const VenueRequestBuilderUriTemplate = "{+baseurl}/participants/hackathons/{hackathonIdOrShortCode%2Did}/venue";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const VenueRequestBuilderNavigationMetadata: Record<Exclude<keyof VenueRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    checkOut: {
        requestsMetadata: CheckOutRequestBuilderRequestsMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
