/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createHackOManiaApiEndpointsOrganizersHackathonOrganizersAddResponseFromDiscriminatorValue, createHackOManiaApiEndpointsOrganizersHackathonOrganizersListResponseFromDiscriminatorValue, serializeHackOManiaApiEndpointsOrganizersHackathonOrganizersAddRequest, serializeHackOManiaApiEndpointsOrganizersHackathonOrganizersAddResponse, type HackOManiaApiEndpointsOrganizersHackathonOrganizersAddRequest, type HackOManiaApiEndpointsOrganizersHackathonOrganizersAddResponse, type HackOManiaApiEndpointsOrganizersHackathonOrganizersListResponse } from '../../../../models/index.js';
// @ts-ignore
import { type WithUserItemRequestBuilder, WithUserItemRequestBuilderRequestsMetadata } from './item/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /organizers/hackathons/{hackathon-id}/organizers
 */
export interface OrganizersRequestBuilder extends BaseRequestBuilder<OrganizersRequestBuilder> {
    /**
     * Gets an item from the ApiSdk.organizers.hackathons.item.organizers.item collection
     * @param userId Unique identifier of the item
     * @returns {WithUserItemRequestBuilder}
     */
     byUserId(userId: string) : WithUserItemRequestBuilder;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<HackOManiaApiEndpointsOrganizersHackathonOrganizersListResponse>}
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<HackOManiaApiEndpointsOrganizersHackathonOrganizersListResponse | undefined>;
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<HackOManiaApiEndpointsOrganizersHackathonOrganizersAddResponse>}
     */
     post(body: HackOManiaApiEndpointsOrganizersHackathonOrganizersAddRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<HackOManiaApiEndpointsOrganizersHackathonOrganizersAddResponse | undefined>;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: HackOManiaApiEndpointsOrganizersHackathonOrganizersAddRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const OrganizersRequestBuilderUriTemplate = "{+baseurl}/organizers/hackathons/{hackathon%2Did}/organizers";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const OrganizersRequestBuilderNavigationMetadata: Record<Exclude<keyof OrganizersRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byUserId: {
        requestsMetadata: WithUserItemRequestBuilderRequestsMetadata,
        pathParametersMappings: ["userId"],
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const OrganizersRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: OrganizersRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "send",
        responseBodyFactory:  createHackOManiaApiEndpointsOrganizersHackathonOrganizersListResponseFromDiscriminatorValue,
    },
    post: {
        uriTemplate: OrganizersRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "send",
        responseBodyFactory:  createHackOManiaApiEndpointsOrganizersHackathonOrganizersAddResponseFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeHackOManiaApiEndpointsOrganizersHackathonOrganizersAddRequest,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
