/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { CheckInRequestBuilderRequestsMetadata, type CheckInRequestBuilder } from './checkIn/index.js';
// @ts-ignore
import { CheckOutRequestBuilderRequestsMetadata, type CheckOutRequestBuilder } from './checkOut/index.js';
// @ts-ignore
import { HistoryRequestBuilderRequestsMetadata, type HistoryRequestBuilder } from './history/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /organizers/hackathons/{hackathonId}/participants/{participantUser-id}/venue
 */
export interface VenueRequestBuilder extends BaseRequestBuilder<VenueRequestBuilder> {
    /**
     * The checkIn property
     */
    get checkIn(): CheckInRequestBuilder;
    /**
     * The checkOut property
     */
    get checkOut(): CheckOutRequestBuilder;
    /**
     * The history property
     */
    get history(): HistoryRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const VenueRequestBuilderUriTemplate = "{+baseurl}/organizers/hackathons/{hackathonId}/participants/{participantUser%2Did}/venue";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const VenueRequestBuilderNavigationMetadata: Record<Exclude<keyof VenueRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    checkIn: {
        requestsMetadata: CheckInRequestBuilderRequestsMetadata,
    },
    checkOut: {
        requestsMetadata: CheckOutRequestBuilderRequestsMetadata,
    },
    history: {
        requestsMetadata: HistoryRequestBuilderRequestsMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
