/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createHackOManiaApiEndpointsOrganizersHackathonParticipantsReviewResponseFromDiscriminatorValue, serializeHackOManiaApiEndpointsOrganizersHackathonParticipantsReviewRequest, serializeHackOManiaApiEndpointsOrganizersHackathonParticipantsReviewResponse, type HackOManiaApiEndpointsOrganizersHackathonParticipantsReviewRequest, type HackOManiaApiEndpointsOrganizersHackathonParticipantsReviewResponse } from '../../../../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /organizers/hackathons/{hackathonId}/participants/{participantUserId}/review
 */
export interface ReviewRequestBuilder extends BaseRequestBuilder<ReviewRequestBuilder> {
    /**
     * Accept or reject a participant's application.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<HackOManiaApiEndpointsOrganizersHackathonParticipantsReviewResponse>}
     */
     post(body: HackOManiaApiEndpointsOrganizersHackathonParticipantsReviewRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<HackOManiaApiEndpointsOrganizersHackathonParticipantsReviewResponse | undefined>;
    /**
     * Accept or reject a participant's application.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: HackOManiaApiEndpointsOrganizersHackathonParticipantsReviewRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const ReviewRequestBuilderUriTemplate = "{+baseurl}/organizers/hackathons/{hackathonId}/participants/{participantUserId}/review";
/**
 * Metadata for all the requests in the request builder.
 */
export const ReviewRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: ReviewRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "send",
        responseBodyFactory:  createHackOManiaApiEndpointsOrganizersHackathonParticipantsReviewResponseFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeHackOManiaApiEndpointsOrganizersHackathonParticipantsReviewRequest,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
