/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createHackOManiaApiEndpointsOrganizersHackathonTimelineUpdateResponseFromDiscriminatorValue, serializeHackOManiaApiEndpointsOrganizersHackathonTimelineUpdateRequest, serializeHackOManiaApiEndpointsOrganizersHackathonTimelineUpdateResponse, type HackOManiaApiEndpointsOrganizersHackathonTimelineUpdateRequest, type HackOManiaApiEndpointsOrganizersHackathonTimelineUpdateResponse } from '../../../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /organizers/hackathons/{hackathonId}/timeline/{timelineItemId}
 */
export interface WithTimelineItemItemRequestBuilder extends BaseRequestBuilder<WithTimelineItemItemRequestBuilder> {
    /**
     * Deletes a timeline item from a hackathon.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     */
     delete(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<void>;
    /**
     * Updates an existing timeline item for a hackathon.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<HackOManiaApiEndpointsOrganizersHackathonTimelineUpdateResponse>}
     */
     patch(body: HackOManiaApiEndpointsOrganizersHackathonTimelineUpdateRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<HackOManiaApiEndpointsOrganizersHackathonTimelineUpdateResponse | undefined>;
    /**
     * Deletes a timeline item from a hackathon.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toDeleteRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
    /**
     * Updates an existing timeline item for a hackathon.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPatchRequestInformation(body: HackOManiaApiEndpointsOrganizersHackathonTimelineUpdateRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const WithTimelineItemItemRequestBuilderUriTemplate = "{+baseurl}/organizers/hackathons/{hackathonId}/timeline/{timelineItemId}";
/**
 * Metadata for all the requests in the request builder.
 */
export const WithTimelineItemItemRequestBuilderRequestsMetadata: RequestsMetadata = {
    delete: {
        uriTemplate: WithTimelineItemItemRequestBuilderUriTemplate,
        adapterMethodName: "sendNoResponseContent",
    },
    patch: {
        uriTemplate: WithTimelineItemItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "send",
        responseBodyFactory:  createHackOManiaApiEndpointsOrganizersHackathonTimelineUpdateResponseFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeHackOManiaApiEndpointsOrganizersHackathonTimelineUpdateRequest,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
