/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createHackOManiaApiEndpointsParticipantsHackathonListResponseFromDiscriminatorValue, type HackOManiaApiEndpointsParticipantsHackathonListResponse } from '../../models/index.js';
// @ts-ignore
import { HackathonIdOrShortCodeItemRequestBuilderNavigationMetadata, HackathonIdOrShortCodeItemRequestBuilderRequestsMetadata, type HackathonIdOrShortCodeItemRequestBuilder } from './item/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /participants/hackathons
 */
export interface HackathonsRequestBuilder extends BaseRequestBuilder<HackathonsRequestBuilder> {
    /**
     * Gets an item from the ApiSdk.participants.hackathons.item collection
     * @param hackathonIdOrShortCodeId Unique identifier of the item
     * @returns {HackathonIdOrShortCodeItemRequestBuilder}
     */
     byHackathonIdOrShortCodeId(hackathonIdOrShortCodeId: string) : HackathonIdOrShortCodeItemRequestBuilder;
    /**
     * Retrieves all published hackathons.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<HackOManiaApiEndpointsParticipantsHackathonListResponse>}
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<HackOManiaApiEndpointsParticipantsHackathonListResponse | undefined>;
    /**
     * Retrieves all published hackathons.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const HackathonsRequestBuilderUriTemplate = "{+baseurl}/participants/hackathons";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const HackathonsRequestBuilderNavigationMetadata: Record<Exclude<keyof HackathonsRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byHackathonIdOrShortCodeId: {
        requestsMetadata: HackathonIdOrShortCodeItemRequestBuilderRequestsMetadata,
        navigationMetadata: HackathonIdOrShortCodeItemRequestBuilderNavigationMetadata,
        pathParametersMappings: ["hackathonIdOrShortCode%2Did"],
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const HackathonsRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: HackathonsRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "send",
        responseBodyFactory:  createHackOManiaApiEndpointsParticipantsHackathonListResponseFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
