/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { type WithResourceItemRequestBuilder, WithResourceItemRequestBuilderNavigationMetadata } from './item/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /organizers/hackathons/{hackathonId}/participants/{participantUser-id}/resources
 */
export interface ResourcesRequestBuilder extends BaseRequestBuilder<ResourcesRequestBuilder> {
    /**
     * Gets an item from the ApiSdk.organizers.hackathons.item.participants.item.resources.item collection
     * @param resourceId Unique identifier of the item
     * @returns {WithResourceItemRequestBuilder}
     */
     byResourceId(resourceId: string) : WithResourceItemRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const ResourcesRequestBuilderUriTemplate = "{+baseurl}/organizers/hackathons/{hackathonId}/participants/{participantUser%2Did}/resources";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const ResourcesRequestBuilderNavigationMetadata: Record<Exclude<keyof ResourcesRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byResourceId: {
        navigationMetadata: WithResourceItemRequestBuilderNavigationMetadata,
        pathParametersMappings: ["resourceId"],
    },
};
/* tslint:enable */
/* eslint-enable */
