/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createHackOManiaApiEndpointsOrganizersHackathonCreateResponseFromDiscriminatorValue, createHackOManiaApiEndpointsOrganizersHackathonListResponseFromDiscriminatorValue, serializeHackOManiaApiEndpointsOrganizersHackathonCreateRequest, serializeHackOManiaApiEndpointsOrganizersHackathonCreateResponse, type HackOManiaApiEndpointsOrganizersHackathonCreateRequest, type HackOManiaApiEndpointsOrganizersHackathonCreateResponse, type HackOManiaApiEndpointsOrganizersHackathonListResponse } from '../../models/index.js';
// @ts-ignore
import { HackathonItemRequestBuilderNavigationMetadata, HackathonItemRequestBuilderRequestsMetadata, type HackathonItemRequestBuilder } from './item/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /organizers/hackathons
 */
export interface HackathonsRequestBuilder extends BaseRequestBuilder<HackathonsRequestBuilder> {
    /**
     * Gets an item from the ApiSdk.organizers.hackathons.item collection
     * @param hackathonId Unique identifier of the item
     * @returns {HackathonItemRequestBuilder}
     */
     byHackathonId(hackathonId: string) : HackathonItemRequestBuilder;
    /**
     * Retrieves all hackathons the current user has organizer access to.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<HackOManiaApiEndpointsOrganizersHackathonListResponse>}
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<HackOManiaApiEndpointsOrganizersHackathonListResponse | undefined>;
    /**
     * Creates a new hackathon event. Permissions depend on the platform configuration.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<HackOManiaApiEndpointsOrganizersHackathonCreateResponse>}
     */
     post(body: HackOManiaApiEndpointsOrganizersHackathonCreateRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<HackOManiaApiEndpointsOrganizersHackathonCreateResponse | undefined>;
    /**
     * Retrieves all hackathons the current user has organizer access to.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
    /**
     * Creates a new hackathon event. Permissions depend on the platform configuration.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: HackOManiaApiEndpointsOrganizersHackathonCreateRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const HackathonsRequestBuilderUriTemplate = "{+baseurl}/organizers/hackathons";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const HackathonsRequestBuilderNavigationMetadata: Record<Exclude<keyof HackathonsRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byHackathonId: {
        requestsMetadata: HackathonItemRequestBuilderRequestsMetadata,
        navigationMetadata: HackathonItemRequestBuilderNavigationMetadata,
        pathParametersMappings: ["hackathon%2Did"],
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const HackathonsRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: HackathonsRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "send",
        responseBodyFactory:  createHackOManiaApiEndpointsOrganizersHackathonListResponseFromDiscriminatorValue,
    },
    post: {
        uriTemplate: HackathonsRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "send",
        responseBodyFactory:  createHackOManiaApiEndpointsOrganizersHackathonCreateResponseFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeHackOManiaApiEndpointsOrganizersHackathonCreateRequest,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
