/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createHackOManiaApiEndpointsParticipantsHackathonTimelineListResponseFromDiscriminatorValue, type HackOManiaApiEndpointsParticipantsHackathonTimelineListResponse } from '../../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /participants/hackathons/{hackathonIdOrShortCode-id}/timeline
 */
export interface TimelineRequestBuilder extends BaseRequestBuilder<TimelineRequestBuilder> {
    /**
     * Retrieves the timeline of events for a hackathon by ID or short code.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<HackOManiaApiEndpointsParticipantsHackathonTimelineListResponse>}
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<HackOManiaApiEndpointsParticipantsHackathonTimelineListResponse | undefined>;
    /**
     * Retrieves the timeline of events for a hackathon by ID or short code.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const TimelineRequestBuilderUriTemplate = "{+baseurl}/participants/hackathons/{hackathonIdOrShortCode%2Did}/timeline";
/**
 * Metadata for all the requests in the request builder.
 */
export const TimelineRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: TimelineRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "send",
        responseBodyFactory:  createHackOManiaApiEndpointsParticipantsHackathonTimelineListResponseFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
