/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createHackOManiaApiEndpointsOrganizersHackathonWorkshopsUpdateResponseFromDiscriminatorValue, serializeHackOManiaApiEndpointsOrganizersHackathonWorkshopsUpdateRequest, serializeHackOManiaApiEndpointsOrganizersHackathonWorkshopsUpdateResponse, type HackOManiaApiEndpointsOrganizersHackathonWorkshopsUpdateRequest, type HackOManiaApiEndpointsOrganizersHackathonWorkshopsUpdateResponse } from '../../../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /organizers/hackathons/{hackathon-id}/workshops/{workshop-id}
 */
export interface WorkshopItemRequestBuilder extends BaseRequestBuilder<WorkshopItemRequestBuilder> {
    /**
     * Deletes an existing workshop.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     */
     delete(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<void>;
    /**
     * Updates an existing workshop.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<HackOManiaApiEndpointsOrganizersHackathonWorkshopsUpdateResponse>}
     */
     put(body: HackOManiaApiEndpointsOrganizersHackathonWorkshopsUpdateRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<HackOManiaApiEndpointsOrganizersHackathonWorkshopsUpdateResponse | undefined>;
    /**
     * Deletes an existing workshop.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toDeleteRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
    /**
     * Updates an existing workshop.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPutRequestInformation(body: HackOManiaApiEndpointsOrganizersHackathonWorkshopsUpdateRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const WorkshopItemRequestBuilderUriTemplate = "{+baseurl}/organizers/hackathons/{hackathon%2Did}/workshops/{workshop%2Did}";
/**
 * Metadata for all the requests in the request builder.
 */
export const WorkshopItemRequestBuilderRequestsMetadata: RequestsMetadata = {
    delete: {
        uriTemplate: WorkshopItemRequestBuilderUriTemplate,
        adapterMethodName: "sendNoResponseContent",
    },
    put: {
        uriTemplate: WorkshopItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "send",
        responseBodyFactory:  createHackOManiaApiEndpointsOrganizersHackathonWorkshopsUpdateResponseFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeHackOManiaApiEndpointsOrganizersHackathonWorkshopsUpdateRequest,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
