/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createHackOManiaApiEndpointsParticipantsHackathonResourcesRedeemResponseFromDiscriminatorValue, type HackOManiaApiEndpointsParticipantsHackathonResourcesRedeemResponse } from '../../../../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /participants/hackathons/{hackathonIdOrShortCode-id}/resources/{resourceId}/redemptions
 */
export interface RedemptionsRequestBuilder extends BaseRequestBuilder<RedemptionsRequestBuilder> {
    /**
     * Creates a redemption record for a resource in the hackathon.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<HackOManiaApiEndpointsParticipantsHackathonResourcesRedeemResponse>}
     */
     post(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<HackOManiaApiEndpointsParticipantsHackathonResourcesRedeemResponse | undefined>;
    /**
     * Creates a redemption record for a resource in the hackathon.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const RedemptionsRequestBuilderUriTemplate = "{+baseurl}/participants/hackathons/{hackathonIdOrShortCode%2Did}/resources/{resourceId}/redemptions";
/**
 * Metadata for all the requests in the request builder.
 */
export const RedemptionsRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: RedemptionsRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "send",
        responseBodyFactory:  createHackOManiaApiEndpointsParticipantsHackathonResourcesRedeemResponseFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
