/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createHackOManiaApiEndpointsOrganizersHackathonJudgesCreateResponseFromDiscriminatorValue, createHackOManiaApiEndpointsOrganizersHackathonJudgesListResponseFromDiscriminatorValue, serializeHackOManiaApiEndpointsOrganizersHackathonJudgesCreateRequest, serializeHackOManiaApiEndpointsOrganizersHackathonJudgesCreateResponse, type HackOManiaApiEndpointsOrganizersHackathonJudgesCreateRequest, type HackOManiaApiEndpointsOrganizersHackathonJudgesCreateResponse, type HackOManiaApiEndpointsOrganizersHackathonJudgesListResponse } from '../../../../models/index.js';
// @ts-ignore
import { type WithJudgeItemRequestBuilder, WithJudgeItemRequestBuilderRequestsMetadata } from './item/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /organizers/hackathons/{hackathonId}/judges
 */
export interface JudgesRequestBuilder extends BaseRequestBuilder<JudgesRequestBuilder> {
    /**
     * Gets an item from the ApiSdk.organizers.hackathons.item.judges.item collection
     * @param judgeId Unique identifier of the item
     * @returns {WithJudgeItemRequestBuilder}
     */
     byJudgeId(judgeId: string) : WithJudgeItemRequestBuilder;
    /**
     * Retrieves all judges for a hackathon including their secrets.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<HackOManiaApiEndpointsOrganizersHackathonJudgesListResponse>}
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<HackOManiaApiEndpointsOrganizersHackathonJudgesListResponse | undefined>;
    /**
     * Creates a new judge for the hackathon. Returns the judge secret that should be shared with the judge for authentication.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<HackOManiaApiEndpointsOrganizersHackathonJudgesCreateResponse>}
     */
     post(body: HackOManiaApiEndpointsOrganizersHackathonJudgesCreateRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<HackOManiaApiEndpointsOrganizersHackathonJudgesCreateResponse | undefined>;
    /**
     * Retrieves all judges for a hackathon including their secrets.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
    /**
     * Creates a new judge for the hackathon. Returns the judge secret that should be shared with the judge for authentication.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: HackOManiaApiEndpointsOrganizersHackathonJudgesCreateRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const JudgesRequestBuilderUriTemplate = "{+baseurl}/organizers/hackathons/{hackathonId}/judges";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const JudgesRequestBuilderNavigationMetadata: Record<Exclude<keyof JudgesRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byJudgeId: {
        requestsMetadata: WithJudgeItemRequestBuilderRequestsMetadata,
        pathParametersMappings: ["judgeId"],
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const JudgesRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: JudgesRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "send",
        responseBodyFactory:  createHackOManiaApiEndpointsOrganizersHackathonJudgesListResponseFromDiscriminatorValue,
    },
    post: {
        uriTemplate: JudgesRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "send",
        responseBodyFactory:  createHackOManiaApiEndpointsOrganizersHackathonJudgesCreateResponseFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeHackOManiaApiEndpointsOrganizersHackathonJudgesCreateRequest,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
