/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createHackOManiaApiEndpointsOrganizersHackathonParticipantsListResponseFromDiscriminatorValue, type HackOManiaApiEndpointsOrganizersHackathonParticipantsListResponse } from '../../../../models/index.js';
// @ts-ignore
import { type WithParticipantUserItemRequestBuilder, WithParticipantUserItemRequestBuilderNavigationMetadata } from './item/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /organizers/hackathons/{hackathon-id}/participants
 */
export interface ParticipantsRequestBuilder extends BaseRequestBuilder<ParticipantsRequestBuilder> {
    /**
     * Gets an item from the ApiSdk.organizers.hackathons.item.participants.item collection
     * @param participantUserId Unique identifier of the item
     * @returns {WithParticipantUserItemRequestBuilder}
     */
     byParticipantUserId(participantUserId: string) : WithParticipantUserItemRequestBuilder;
    /**
     * Retrieves all participants for a hackathon with their review status.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<HackOManiaApiEndpointsOrganizersHackathonParticipantsListResponse>}
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<HackOManiaApiEndpointsOrganizersHackathonParticipantsListResponse | undefined>;
    /**
     * Retrieves all participants for a hackathon with their review status.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const ParticipantsRequestBuilderUriTemplate = "{+baseurl}/organizers/hackathons/{hackathon%2Did}/participants";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const ParticipantsRequestBuilderNavigationMetadata: Record<Exclude<keyof ParticipantsRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byParticipantUserId: {
        navigationMetadata: WithParticipantUserItemRequestBuilderNavigationMetadata,
        pathParametersMappings: ["participantUserId"],
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const ParticipantsRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: ParticipantsRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "send",
        responseBodyFactory:  createHackOManiaApiEndpointsOrganizersHackathonParticipantsListResponseFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
