/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createHackOManiaApiEndpointsParticipantsHackathonWithdrawResponseFromDiscriminatorValue, type HackOManiaApiEndpointsParticipantsHackathonWithdrawResponse } from '../../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /participants/hackathons/{hackathonIdOrShortCode-id}/withdraw
 */
export interface WithdrawRequestBuilder extends BaseRequestBuilder<WithdrawRequestBuilder> {
    /**
     * Withdraws the current user from the hackathon. The participant must not be in a team before withdrawing.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<HackOManiaApiEndpointsParticipantsHackathonWithdrawResponse>}
     */
     post(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<HackOManiaApiEndpointsParticipantsHackathonWithdrawResponse | undefined>;
    /**
     * Withdraws the current user from the hackathon. The participant must not be in a team before withdrawing.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const WithdrawRequestBuilderUriTemplate = "{+baseurl}/participants/hackathons/{hackathonIdOrShortCode%2Did}/withdraw";
/**
 * Metadata for all the requests in the request builder.
 */
export const WithdrawRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: WithdrawRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "send",
        responseBodyFactory:  createHackOManiaApiEndpointsParticipantsHackathonWithdrawResponseFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
