/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { HackathonsRequestBuilderNavigationMetadata, HackathonsRequestBuilderRequestsMetadata, type HackathonsRequestBuilder } from './hackathons/index.js';
// @ts-ignore
import { TeamsRequestBuilderNavigationMetadata, type TeamsRequestBuilder } from './teams/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /participants
 */
export interface ParticipantsRequestBuilder extends BaseRequestBuilder<ParticipantsRequestBuilder> {
    /**
     * The hackathons property
     */
    get hackathons(): HackathonsRequestBuilder;
    /**
     * The teams property
     */
    get teams(): TeamsRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const ParticipantsRequestBuilderUriTemplate = "{+baseurl}/participants";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const ParticipantsRequestBuilderNavigationMetadata: Record<Exclude<keyof ParticipantsRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    hackathons: {
        requestsMetadata: HackathonsRequestBuilderRequestsMetadata,
        navigationMetadata: HackathonsRequestBuilderNavigationMetadata,
    },
    teams: {
        navigationMetadata: TeamsRequestBuilderNavigationMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
