/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createHackOManiaApiEndpointsOrganizersHackathonParticipantsWithdrawResponseFromDiscriminatorValue, type HackOManiaApiEndpointsOrganizersHackathonParticipantsWithdrawResponse } from '../../../../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /organizers/hackathons/{hackathonId}/participants/{participantUser-id}/withdraw
 */
export interface WithdrawRequestBuilder extends BaseRequestBuilder<WithdrawRequestBuilder> {
    /**
     * Withdraws a participant from the hackathon. Organizers can withdraw any active participant.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<HackOManiaApiEndpointsOrganizersHackathonParticipantsWithdrawResponse>}
     */
     post(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<HackOManiaApiEndpointsOrganizersHackathonParticipantsWithdrawResponse | undefined>;
    /**
     * Withdraws a participant from the hackathon. Organizers can withdraw any active participant.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const WithdrawRequestBuilderUriTemplate = "{+baseurl}/organizers/hackathons/{hackathonId}/participants/{participantUser%2Did}/withdraw";
/**
 * Metadata for all the requests in the request builder.
 */
export const WithdrawRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: WithdrawRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "send",
        responseBodyFactory:  createHackOManiaApiEndpointsOrganizersHackathonParticipantsWithdrawResponseFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
