/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createHackOManiaApiEndpointsAuthWhoAmIResponseFromDiscriminatorValue, type HackOManiaApiEndpointsAuthWhoAmIResponse } from '../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /auth/whoami
 */
export interface WhoamiRequestBuilder extends BaseRequestBuilder<WhoamiRequestBuilder> {
    /**
     * Returns the current authenticated user's information including GitHub details.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<HackOManiaApiEndpointsAuthWhoAmIResponse>}
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<HackOManiaApiEndpointsAuthWhoAmIResponse | undefined>;
    /**
     * Returns the current authenticated user's information including GitHub details.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const WhoamiRequestBuilderUriTemplate = "{+baseurl}/auth/whoami";
/**
 * Metadata for all the requests in the request builder.
 */
export const WhoamiRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: WhoamiRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "send",
        responseBodyFactory:  createHackOManiaApiEndpointsAuthWhoAmIResponseFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
