/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createHackOManiaApiEndpointsParticipantsHackathonWorkshopsListResponseFromDiscriminatorValue, type HackOManiaApiEndpointsParticipantsHackathonWorkshopsListResponse } from '../../../../models/index.js';
// @ts-ignore
import { type WithWorkshopItemRequestBuilder, WithWorkshopItemRequestBuilderNavigationMetadata } from './item/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /participants/hackathons/{hackathonIdOrShortCode-id}/workshops
 */
export interface WorkshopsRequestBuilder extends BaseRequestBuilder<WorkshopsRequestBuilder> {
    /**
     * Gets an item from the ApiSdk.participants.hackathons.item.workshops.item collection
     * @param workshopId Unique identifier of the item
     * @returns {WithWorkshopItemRequestBuilder}
     */
     byWorkshopId(workshopId: string) : WithWorkshopItemRequestBuilder;
    /**
     * Lists all published workshops for the hackathon.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<HackOManiaApiEndpointsParticipantsHackathonWorkshopsListResponse>}
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<HackOManiaApiEndpointsParticipantsHackathonWorkshopsListResponse | undefined>;
    /**
     * Lists all published workshops for the hackathon.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const WorkshopsRequestBuilderUriTemplate = "{+baseurl}/participants/hackathons/{hackathonIdOrShortCode%2Did}/workshops";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const WorkshopsRequestBuilderNavigationMetadata: Record<Exclude<keyof WorkshopsRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byWorkshopId: {
        navigationMetadata: WithWorkshopItemRequestBuilderNavigationMetadata,
        pathParametersMappings: ["workshopId"],
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const WorkshopsRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: WorkshopsRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "send",
        responseBodyFactory:  createHackOManiaApiEndpointsParticipantsHackathonWorkshopsListResponseFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
