/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createHackOManiaApiEndpointsParticipantsHackathonTeamsRemoveMemberResponseFromDiscriminatorValue, type HackOManiaApiEndpointsParticipantsHackathonTeamsRemoveMemberResponse } from '../../../../../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /participants/hackathons/{hackathonIdOrShortCode-id}/teams/{teamId}/members/{userId}
 */
export interface WithUserItemRequestBuilder extends BaseRequestBuilder<WithUserItemRequestBuilder> {
    /**
     * Allows the team member to remove another member from the team. Cannot remove yourself (use leave endpoint instead). If no members remain after removal, the team will be deleted.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<HackOManiaApiEndpointsParticipantsHackathonTeamsRemoveMemberResponse>}
     */
     delete(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<HackOManiaApiEndpointsParticipantsHackathonTeamsRemoveMemberResponse | undefined>;
    /**
     * Allows the team member to remove another member from the team. Cannot remove yourself (use leave endpoint instead). If no members remain after removal, the team will be deleted.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toDeleteRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const WithUserItemRequestBuilderUriTemplate = "{+baseurl}/participants/hackathons/{hackathonIdOrShortCode%2Did}/teams/{teamId}/members/{userId}";
/**
 * Metadata for all the requests in the request builder.
 */
export const WithUserItemRequestBuilderRequestsMetadata: RequestsMetadata = {
    delete: {
        uriTemplate: WithUserItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "send",
        responseBodyFactory:  createHackOManiaApiEndpointsParticipantsHackathonTeamsRemoveMemberResponseFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
