/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createHackOManiaApiEndpointsParticipantsHackathonJoinResponseFromDiscriminatorValue, type HackOManiaApiEndpointsParticipantsHackathonJoinResponse } from '../../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /participants/hackathons/{id}/join
 */
export interface JoinRequestBuilder extends BaseRequestBuilder<JoinRequestBuilder> {
    /**
     * Registers the current user as a participant in the hackathon.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<HackOManiaApiEndpointsParticipantsHackathonJoinResponse>}
     */
     post(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<HackOManiaApiEndpointsParticipantsHackathonJoinResponse | undefined>;
    /**
     * Registers the current user as a participant in the hackathon.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const JoinRequestBuilderUriTemplate = "{+baseurl}/participants/hackathons/{id}/join";
/**
 * Metadata for all the requests in the request builder.
 */
export const JoinRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: JoinRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "send",
        responseBodyFactory:  createHackOManiaApiEndpointsParticipantsHackathonJoinResponseFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
