/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createFastEndpointsErrorResponseFromDiscriminatorValue, createHackOManiaApiEndpointsParticipantsHackathonTeamsSelectChallengeResponseFromDiscriminatorValue, serializeHackOManiaApiEndpointsParticipantsHackathonTeamsSelectChallengeRequest, serializeHackOManiaApiEndpointsParticipantsHackathonTeamsSelectChallengeResponse, type FastEndpointsErrorResponse, type HackOManiaApiEndpointsParticipantsHackathonTeamsSelectChallengeRequest, type HackOManiaApiEndpointsParticipantsHackathonTeamsSelectChallengeResponse } from '../../../../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /participants/hackathons/{hackathonIdOrShortCode-id}/teams/{teamId}/challenge
 */
export interface ChallengeRequestBuilder extends BaseRequestBuilder<ChallengeRequestBuilder> {
    /**
     * Updates the team's selected challenge.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<HackOManiaApiEndpointsParticipantsHackathonTeamsSelectChallengeResponse>}
     * @throws {FastEndpointsErrorResponse} error when the service returns a 400 status code
     */
     put(body: HackOManiaApiEndpointsParticipantsHackathonTeamsSelectChallengeRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<HackOManiaApiEndpointsParticipantsHackathonTeamsSelectChallengeResponse | undefined>;
    /**
     * Updates the team's selected challenge.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPutRequestInformation(body: HackOManiaApiEndpointsParticipantsHackathonTeamsSelectChallengeRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const ChallengeRequestBuilderUriTemplate = "{+baseurl}/participants/hackathons/{hackathonIdOrShortCode%2Did}/teams/{teamId}/challenge";
/**
 * Metadata for all the requests in the request builder.
 */
export const ChallengeRequestBuilderRequestsMetadata: RequestsMetadata = {
    put: {
        uriTemplate: ChallengeRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createFastEndpointsErrorResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createHackOManiaApiEndpointsParticipantsHackathonTeamsSelectChallengeResponseFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeHackOManiaApiEndpointsParticipantsHackathonTeamsSelectChallengeRequest,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
