/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createHackOManiaApiEndpointsParticipantsHackathonChallengesListResponseFromDiscriminatorValue, type HackOManiaApiEndpointsParticipantsHackathonChallengesListResponse } from '../../../../models/index.js';
// @ts-ignore
import { type WithChallengeItemRequestBuilder, WithChallengeItemRequestBuilderRequestsMetadata } from './item/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /participants/hackathons/{hackathonIdOrShortCode-id}/challenges
 */
export interface ChallengesRequestBuilder extends BaseRequestBuilder<ChallengesRequestBuilder> {
    /**
     * Gets an item from the ApiSdk.participants.hackathons.item.challenges.item collection
     * @param challengeId Unique identifier of the item
     * @returns {WithChallengeItemRequestBuilder}
     */
     byChallengeId(challengeId: string) : WithChallengeItemRequestBuilder;
    /**
     * Retrieves all published challenges for a hackathon.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<HackOManiaApiEndpointsParticipantsHackathonChallengesListResponse>}
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<HackOManiaApiEndpointsParticipantsHackathonChallengesListResponse | undefined>;
    /**
     * Retrieves all published challenges for a hackathon.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const ChallengesRequestBuilderUriTemplate = "{+baseurl}/participants/hackathons/{hackathonIdOrShortCode%2Did}/challenges";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const ChallengesRequestBuilderNavigationMetadata: Record<Exclude<keyof ChallengesRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byChallengeId: {
        requestsMetadata: WithChallengeItemRequestBuilderRequestsMetadata,
        pathParametersMappings: ["challengeId"],
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const ChallengesRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: ChallengesRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "send",
        responseBodyFactory:  createHackOManiaApiEndpointsParticipantsHackathonChallengesListResponseFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
