/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createFastEndpointsErrorResponseFromDiscriminatorValue, createHackOManiaApiEndpointsParticipantsHackathonRegistrationSubmissionsListResponseFromDiscriminatorValue, createHackOManiaApiEndpointsParticipantsHackathonRegistrationSubmissionsSubmitResponseFromDiscriminatorValue, serializeHackOManiaApiEndpointsParticipantsHackathonRegistrationSubmissionsSubmitRequest, serializeHackOManiaApiEndpointsParticipantsHackathonRegistrationSubmissionsSubmitResponse, type FastEndpointsErrorResponse, type HackOManiaApiEndpointsParticipantsHackathonRegistrationSubmissionsListResponse, type HackOManiaApiEndpointsParticipantsHackathonRegistrationSubmissionsSubmitRequest, type HackOManiaApiEndpointsParticipantsHackathonRegistrationSubmissionsSubmitResponse } from '../../../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /participants/hackathons/{hackathonIdOrShortCode-id}/registration/submissions
 */
export interface SubmissionsRequestBuilder extends BaseRequestBuilder<SubmissionsRequestBuilder> {
    /**
     * Get the current user's registration submissions for a hackathon.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<HackOManiaApiEndpointsParticipantsHackathonRegistrationSubmissionsListResponse>}
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<HackOManiaApiEndpointsParticipantsHackathonRegistrationSubmissionsListResponse | undefined>;
    /**
     * Submit or update answers to registration questions. Existing answers will be replaced.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<HackOManiaApiEndpointsParticipantsHackathonRegistrationSubmissionsSubmitResponse>}
     * @throws {FastEndpointsErrorResponse} error when the service returns a 400 status code
     */
     post(body: HackOManiaApiEndpointsParticipantsHackathonRegistrationSubmissionsSubmitRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<HackOManiaApiEndpointsParticipantsHackathonRegistrationSubmissionsSubmitResponse | undefined>;
    /**
     * Get the current user's registration submissions for a hackathon.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
    /**
     * Submit or update answers to registration questions. Existing answers will be replaced.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: HackOManiaApiEndpointsParticipantsHackathonRegistrationSubmissionsSubmitRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const SubmissionsRequestBuilderUriTemplate = "{+baseurl}/participants/hackathons/{hackathonIdOrShortCode%2Did}/registration/submissions";
/**
 * Metadata for all the requests in the request builder.
 */
export const SubmissionsRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: SubmissionsRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "send",
        responseBodyFactory:  createHackOManiaApiEndpointsParticipantsHackathonRegistrationSubmissionsListResponseFromDiscriminatorValue,
    },
    post: {
        uriTemplate: SubmissionsRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createFastEndpointsErrorResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createHackOManiaApiEndpointsParticipantsHackathonRegistrationSubmissionsSubmitResponseFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeHackOManiaApiEndpointsParticipantsHackathonRegistrationSubmissionsSubmitRequest,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
