/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createHackOManiaApiEndpointsParticipantsHackathonJoinByShortCodeResponseFromDiscriminatorValue, serializeHackOManiaApiEndpointsParticipantsHackathonJoinByShortCodeRequest, serializeHackOManiaApiEndpointsParticipantsHackathonJoinByShortCodeResponse, type HackOManiaApiEndpointsParticipantsHackathonJoinByShortCodeRequest, type HackOManiaApiEndpointsParticipantsHackathonJoinByShortCodeResponse } from '../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /participants/hackathons/join
 */
export interface JoinRequestBuilder extends BaseRequestBuilder<JoinRequestBuilder> {
    /**
     * Registers the current user as a participant in the hackathon using the hackathon's short code.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<HackOManiaApiEndpointsParticipantsHackathonJoinByShortCodeResponse>}
     */
     post(body: HackOManiaApiEndpointsParticipantsHackathonJoinByShortCodeRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<HackOManiaApiEndpointsParticipantsHackathonJoinByShortCodeResponse | undefined>;
    /**
     * Registers the current user as a participant in the hackathon using the hackathon's short code.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: HackOManiaApiEndpointsParticipantsHackathonJoinByShortCodeRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const JoinRequestBuilderUriTemplate = "{+baseurl}/participants/hackathons/join";
/**
 * Metadata for all the requests in the request builder.
 */
export const JoinRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: JoinRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "send",
        responseBodyFactory:  createHackOManiaApiEndpointsParticipantsHackathonJoinByShortCodeResponseFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeHackOManiaApiEndpointsParticipantsHackathonJoinByShortCodeRequest,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
