/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { QuestionsRequestBuilderNavigationMetadata, QuestionsRequestBuilderRequestsMetadata, type QuestionsRequestBuilder } from './questions/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /organizers/hackathons/{hackathon-id}/registration
 */
export interface RegistrationRequestBuilder extends BaseRequestBuilder<RegistrationRequestBuilder> {
    /**
     * The questions property
     */
    get questions(): QuestionsRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const RegistrationRequestBuilderUriTemplate = "{+baseurl}/organizers/hackathons/{hackathon%2Did}/registration";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const RegistrationRequestBuilderNavigationMetadata: Record<Exclude<keyof RegistrationRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    questions: {
        requestsMetadata: QuestionsRequestBuilderRequestsMetadata,
        navigationMetadata: QuestionsRequestBuilderNavigationMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
