/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createHackOManiaApiEndpointsOrganizersHackathonResourcesRedeemResponseFromDiscriminatorValue, type HackOManiaApiEndpointsOrganizersHackathonResourcesRedeemResponse } from '../../../../../../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /organizers/hackathons/{hackathonId}/participants/{participantUser-id}/resources/{resourceId}/redemptions
 */
export interface RedemptionsRequestBuilder extends BaseRequestBuilder<RedemptionsRequestBuilder> {
    /**
     * Creates a redemption record for a resource in the hackathon on behalf of a participant.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<HackOManiaApiEndpointsOrganizersHackathonResourcesRedeemResponse>}
     */
     post(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<HackOManiaApiEndpointsOrganizersHackathonResourcesRedeemResponse | undefined>;
    /**
     * Creates a redemption record for a resource in the hackathon on behalf of a participant.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const RedemptionsRequestBuilderUriTemplate = "{+baseurl}/organizers/hackathons/{hackathonId}/participants/{participantUser%2Did}/resources/{resourceId}/redemptions";
/**
 * Metadata for all the requests in the request builder.
 */
export const RedemptionsRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: RedemptionsRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "send",
        responseBodyFactory:  createHackOManiaApiEndpointsOrganizersHackathonResourcesRedeemResponseFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
