/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { OverviewRequestBuilderRequestsMetadata, type OverviewRequestBuilder } from './overview/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /organizers/hackathons/{hackathonId}/venue
 */
export interface VenueRequestBuilder extends BaseRequestBuilder<VenueRequestBuilder> {
    /**
     * The overview property
     */
    get overview(): OverviewRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const VenueRequestBuilderUriTemplate = "{+baseurl}/organizers/hackathons/{hackathonId}/venue";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const VenueRequestBuilderNavigationMetadata: Record<Exclude<keyof VenueRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    overview: {
        requestsMetadata: OverviewRequestBuilderRequestsMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
