/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createHackOManiaApiEndpointsOrganizersHackathonVenueCheckOutResponseFromDiscriminatorValue, type HackOManiaApiEndpointsOrganizersHackathonVenueCheckOutResponse } from '../../../../../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /organizers/hackathons/{hackathonId}/participants/{participantUser-id}/venue/check-out
 */
export interface CheckOutRequestBuilder extends BaseRequestBuilder<CheckOutRequestBuilder> {
    /**
     * Checks a participant out from the hackathon venue.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<HackOManiaApiEndpointsOrganizersHackathonVenueCheckOutResponse>}
     */
     post(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<HackOManiaApiEndpointsOrganizersHackathonVenueCheckOutResponse | undefined>;
    /**
     * Checks a participant out from the hackathon venue.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const CheckOutRequestBuilderUriTemplate = "{+baseurl}/organizers/hackathons/{hackathonId}/participants/{participantUser%2Did}/venue/check-out";
/**
 * Metadata for all the requests in the request builder.
 */
export const CheckOutRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: CheckOutRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "send",
        responseBodyFactory:  createHackOManiaApiEndpointsOrganizersHackathonVenueCheckOutResponseFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
