/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { AttendanceRequestBuilderRequestsMetadata, type AttendanceRequestBuilder } from './attendance/index.js';
// @ts-ignore
import { JoinRequestBuilderRequestsMetadata, type JoinRequestBuilder } from './join/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /participants/hackathons/{hackathonIdOrShortCode-id}/workshops/{workshopId}
 */
export interface WithWorkshopItemRequestBuilder extends BaseRequestBuilder<WithWorkshopItemRequestBuilder> {
    /**
     * The attendance property
     */
    get attendance(): AttendanceRequestBuilder;
    /**
     * The join property
     */
    get join(): JoinRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const WithWorkshopItemRequestBuilderUriTemplate = "{+baseurl}/participants/hackathons/{hackathonIdOrShortCode%2Did}/workshops/{workshopId}";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const WithWorkshopItemRequestBuilderNavigationMetadata: Record<Exclude<keyof WithWorkshopItemRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    attendance: {
        requestsMetadata: AttendanceRequestBuilderRequestsMetadata,
    },
    join: {
        requestsMetadata: JoinRequestBuilderRequestsMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
