/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createHackOManiaApiEndpointsOrganizersHackathonRegistrationQuestionsInitializeResponseFromDiscriminatorValue, type HackOManiaApiEndpointsOrganizersHackathonRegistrationQuestionsInitializeResponse } from '../../../../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /organizers/hackathons/{hackathon-id}/registration/questions/initialize
 */
export interface InitializeRequestBuilder extends BaseRequestBuilder<InitializeRequestBuilder> {
    /**
     * Create a standard set of registration questions for the hackathon. Will not create if questions already exist.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<HackOManiaApiEndpointsOrganizersHackathonRegistrationQuestionsInitializeResponse>}
     */
     post(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<HackOManiaApiEndpointsOrganizersHackathonRegistrationQuestionsInitializeResponse | undefined>;
    /**
     * Create a standard set of registration questions for the hackathon. Will not create if questions already exist.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const InitializeRequestBuilderUriTemplate = "{+baseurl}/organizers/hackathons/{hackathon%2Did}/registration/questions/initialize";
/**
 * Metadata for all the requests in the request builder.
 */
export const InitializeRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: InitializeRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "send",
        responseBodyFactory:  createHackOManiaApiEndpointsOrganizersHackathonRegistrationQuestionsInitializeResponseFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
