/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createHackOManiaApiEndpointsParticipantsHackathonTeamsUpdateResponseFromDiscriminatorValue, serializeHackOManiaApiEndpointsParticipantsHackathonTeamsUpdateRequest, serializeHackOManiaApiEndpointsParticipantsHackathonTeamsUpdateResponse, type HackOManiaApiEndpointsParticipantsHackathonTeamsUpdateRequest, type HackOManiaApiEndpointsParticipantsHackathonTeamsUpdateResponse } from '../../../../../models/index.js';
// @ts-ignore
import { JoinRequestBuilderRequestsMetadata, type JoinRequestBuilder } from './join/index.js';
// @ts-ignore
import { SubmissionsRequestBuilderRequestsMetadata, type SubmissionsRequestBuilder } from './submissions/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /participants/hackathons/{hackathonIdOrShortCode-id}/teams/{teamId}
 */
export interface WithTeamItemRequestBuilder extends BaseRequestBuilder<WithTeamItemRequestBuilder> {
    /**
     * The join property
     */
    get join(): JoinRequestBuilder;
    /**
     * The submissions property
     */
    get submissions(): SubmissionsRequestBuilder;
    /**
     * Updates the team name and description. Only team members can update.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<HackOManiaApiEndpointsParticipantsHackathonTeamsUpdateResponse>}
     */
     patch(body: HackOManiaApiEndpointsParticipantsHackathonTeamsUpdateRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<HackOManiaApiEndpointsParticipantsHackathonTeamsUpdateResponse | undefined>;
    /**
     * Updates the team name and description. Only team members can update.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPatchRequestInformation(body: HackOManiaApiEndpointsParticipantsHackathonTeamsUpdateRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const WithTeamItemRequestBuilderUriTemplate = "{+baseurl}/participants/hackathons/{hackathonIdOrShortCode%2Did}/teams/{teamId}";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const WithTeamItemRequestBuilderNavigationMetadata: Record<Exclude<keyof WithTeamItemRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    join: {
        requestsMetadata: JoinRequestBuilderRequestsMetadata,
    },
    submissions: {
        requestsMetadata: SubmissionsRequestBuilderRequestsMetadata,
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const WithTeamItemRequestBuilderRequestsMetadata: RequestsMetadata = {
    patch: {
        uriTemplate: WithTeamItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "send",
        responseBodyFactory:  createHackOManiaApiEndpointsParticipantsHackathonTeamsUpdateResponseFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeHackOManiaApiEndpointsParticipantsHackathonTeamsUpdateRequest,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
