/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { QuestionsRequestBuilderRequestsMetadata, type QuestionsRequestBuilder } from './questions/index.js';
// @ts-ignore
import { SubmissionsRequestBuilderRequestsMetadata, type SubmissionsRequestBuilder } from './submissions/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /participants/hackathons/{hackathonIdOrShortCode-id}/registration
 */
export interface RegistrationRequestBuilder extends BaseRequestBuilder<RegistrationRequestBuilder> {
    /**
     * The questions property
     */
    get questions(): QuestionsRequestBuilder;
    /**
     * The submissions property
     */
    get submissions(): SubmissionsRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const RegistrationRequestBuilderUriTemplate = "{+baseurl}/participants/hackathons/{hackathonIdOrShortCode%2Did}/registration";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const RegistrationRequestBuilderNavigationMetadata: Record<Exclude<keyof RegistrationRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    questions: {
        requestsMetadata: QuestionsRequestBuilderRequestsMetadata,
    },
    submissions: {
        requestsMetadata: SubmissionsRequestBuilderRequestsMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
