/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { type WithUserItemRequestBuilder, WithUserItemRequestBuilderRequestsMetadata } from './item/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /participants/hackathons/{hackathonIdOrShortCode-id}/teams/{teamId}/members
 */
export interface MembersRequestBuilder extends BaseRequestBuilder<MembersRequestBuilder> {
    /**
     * Gets an item from the ApiSdk.participants.hackathons.item.teams.item.members.item collection
     * @param userId Unique identifier of the item
     * @returns {WithUserItemRequestBuilder}
     */
     byUserId(userId: string) : WithUserItemRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const MembersRequestBuilderUriTemplate = "{+baseurl}/participants/hackathons/{hackathonIdOrShortCode%2Did}/teams/{teamId}/members";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const MembersRequestBuilderNavigationMetadata: Record<Exclude<keyof MembersRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byUserId: {
        requestsMetadata: WithUserItemRequestBuilderRequestsMetadata,
        pathParametersMappings: ["userId"],
    },
};
/* tslint:enable */
/* eslint-enable */
