/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createHackOManiaApiEndpointsParticipantsHackathonWorkshopsJoinResponseFromDiscriminatorValue, type HackOManiaApiEndpointsParticipantsHackathonWorkshopsJoinResponse } from '../../../../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /participants/hackathons/{hackathonIdOrShortCode-id}/workshops/{workshopId}/join
 */
export interface JoinRequestBuilder extends BaseRequestBuilder<JoinRequestBuilder> {
    /**
     * Join a workshop as a participant.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<HackOManiaApiEndpointsParticipantsHackathonWorkshopsJoinResponse>}
     */
     post(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<HackOManiaApiEndpointsParticipantsHackathonWorkshopsJoinResponse | undefined>;
    /**
     * Join a workshop as a participant.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const JoinRequestBuilderUriTemplate = "{+baseurl}/participants/hackathons/{hackathonIdOrShortCode%2Did}/workshops/{workshopId}/join";
/**
 * Metadata for all the requests in the request builder.
 */
export const JoinRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: JoinRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "send",
        responseBodyFactory:  createHackOManiaApiEndpointsParticipantsHackathonWorkshopsJoinResponseFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
