/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createHackOManiaApiEndpointsOrganizersHackathonWorkshopsCreateResponseFromDiscriminatorValue, createHackOManiaApiEndpointsOrganizersHackathonWorkshopsListResponseFromDiscriminatorValue, serializeHackOManiaApiEndpointsOrganizersHackathonWorkshopsCreateRequest, serializeHackOManiaApiEndpointsOrganizersHackathonWorkshopsCreateResponse, type HackOManiaApiEndpointsOrganizersHackathonWorkshopsCreateRequest, type HackOManiaApiEndpointsOrganizersHackathonWorkshopsCreateResponse, type HackOManiaApiEndpointsOrganizersHackathonWorkshopsListResponse } from '../../../../models/index.js';
// @ts-ignore
import { type WithWorkshopItemRequestBuilder, WithWorkshopItemRequestBuilderRequestsMetadata } from './item/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /organizers/hackathons/{hackathonId}/workshops
 */
export interface WorkshopsRequestBuilder extends BaseRequestBuilder<WorkshopsRequestBuilder> {
    /**
     * Gets an item from the ApiSdk.organizers.hackathons.item.workshops.item collection
     * @param workshopId Unique identifier of the item
     * @returns {WithWorkshopItemRequestBuilder}
     */
     byWorkshopId(workshopId: string) : WithWorkshopItemRequestBuilder;
    /**
     * Lists all workshops for the hackathon.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<HackOManiaApiEndpointsOrganizersHackathonWorkshopsListResponse>}
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<HackOManiaApiEndpointsOrganizersHackathonWorkshopsListResponse | undefined>;
    /**
     * Creates a new workshop for the hackathon.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<HackOManiaApiEndpointsOrganizersHackathonWorkshopsCreateResponse>}
     */
     post(body: HackOManiaApiEndpointsOrganizersHackathonWorkshopsCreateRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<HackOManiaApiEndpointsOrganizersHackathonWorkshopsCreateResponse | undefined>;
    /**
     * Lists all workshops for the hackathon.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
    /**
     * Creates a new workshop for the hackathon.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: HackOManiaApiEndpointsOrganizersHackathonWorkshopsCreateRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const WorkshopsRequestBuilderUriTemplate = "{+baseurl}/organizers/hackathons/{hackathonId}/workshops";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const WorkshopsRequestBuilderNavigationMetadata: Record<Exclude<keyof WorkshopsRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byWorkshopId: {
        requestsMetadata: WithWorkshopItemRequestBuilderRequestsMetadata,
        pathParametersMappings: ["workshopId"],
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const WorkshopsRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: WorkshopsRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "send",
        responseBodyFactory:  createHackOManiaApiEndpointsOrganizersHackathonWorkshopsListResponseFromDiscriminatorValue,
    },
    post: {
        uriTemplate: WorkshopsRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "send",
        responseBodyFactory:  createHackOManiaApiEndpointsOrganizersHackathonWorkshopsCreateResponseFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeHackOManiaApiEndpointsOrganizersHackathonWorkshopsCreateRequest,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
