/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { type WithSubmissionItemRequestBuilder, WithSubmissionItemRequestBuilderRequestsMetadata } from './item/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /participants/hackathons/{id}/submissions
 */
export interface SubmissionsRequestBuilder extends BaseRequestBuilder<SubmissionsRequestBuilder> {
    /**
     * Gets an item from the ApiSdk.participants.hackathons.item.submissions.item collection
     * @param submissionId Unique identifier of the item
     * @returns {WithSubmissionItemRequestBuilder}
     */
     bySubmissionId(submissionId: string) : WithSubmissionItemRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const SubmissionsRequestBuilderUriTemplate = "{+baseurl}/participants/hackathons/{id}/submissions";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const SubmissionsRequestBuilderNavigationMetadata: Record<Exclude<keyof SubmissionsRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    bySubmissionId: {
        requestsMetadata: WithSubmissionItemRequestBuilderRequestsMetadata,
        pathParametersMappings: ["submissionId"],
    },
};
/* tslint:enable */
/* eslint-enable */
