/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createHackOManiaApiEndpointsParticipantsHackathonWorkshopsMarkAttendanceResponseFromDiscriminatorValue, type HackOManiaApiEndpointsParticipantsHackathonWorkshopsMarkAttendanceResponse } from '../../../../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /participants/hackathons/{hackathonIdOrShortCode-id}/workshops/{workshopId}/attendance
 */
export interface AttendanceRequestBuilder extends BaseRequestBuilder<AttendanceRequestBuilder> {
    /**
     * Mark attendance for a workshop that the participant has joined.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<HackOManiaApiEndpointsParticipantsHackathonWorkshopsMarkAttendanceResponse>}
     */
     post(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<HackOManiaApiEndpointsParticipantsHackathonWorkshopsMarkAttendanceResponse | undefined>;
    /**
     * Mark attendance for a workshop that the participant has joined.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const AttendanceRequestBuilderUriTemplate = "{+baseurl}/participants/hackathons/{hackathonIdOrShortCode%2Did}/workshops/{workshopId}/attendance";
/**
 * Metadata for all the requests in the request builder.
 */
export const AttendanceRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: AttendanceRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "send",
        responseBodyFactory:  createHackOManiaApiEndpointsParticipantsHackathonWorkshopsMarkAttendanceResponseFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
