/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createHackOManiaApiEndpointsOrganizersHackathonTimelineCreateResponseFromDiscriminatorValue, serializeHackOManiaApiEndpointsOrganizersHackathonTimelineCreateRequest, serializeHackOManiaApiEndpointsOrganizersHackathonTimelineCreateResponse, type HackOManiaApiEndpointsOrganizersHackathonTimelineCreateRequest, type HackOManiaApiEndpointsOrganizersHackathonTimelineCreateResponse } from '../../../../models/index.js';
// @ts-ignore
import { type WithTimelineItemItemRequestBuilder, WithTimelineItemItemRequestBuilderRequestsMetadata } from './item/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /organizers/hackathons/{hackathonId}/timeline
 */
export interface TimelineRequestBuilder extends BaseRequestBuilder<TimelineRequestBuilder> {
    /**
     * Gets an item from the ApiSdk.organizers.hackathons.item.timeline.item collection
     * @param timelineItemId Unique identifier of the item
     * @returns {WithTimelineItemItemRequestBuilder}
     */
     byTimelineItemId(timelineItemId: string) : WithTimelineItemItemRequestBuilder;
    /**
     * Creates a new timeline item for a hackathon.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<HackOManiaApiEndpointsOrganizersHackathonTimelineCreateResponse>}
     */
     post(body: HackOManiaApiEndpointsOrganizersHackathonTimelineCreateRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<HackOManiaApiEndpointsOrganizersHackathonTimelineCreateResponse | undefined>;
    /**
     * Creates a new timeline item for a hackathon.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: HackOManiaApiEndpointsOrganizersHackathonTimelineCreateRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const TimelineRequestBuilderUriTemplate = "{+baseurl}/organizers/hackathons/{hackathonId}/timeline";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const TimelineRequestBuilderNavigationMetadata: Record<Exclude<keyof TimelineRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byTimelineItemId: {
        requestsMetadata: WithTimelineItemItemRequestBuilderRequestsMetadata,
        pathParametersMappings: ["timelineItemId"],
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const TimelineRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: TimelineRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "send",
        responseBodyFactory:  createHackOManiaApiEndpointsOrganizersHackathonTimelineCreateResponseFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeHackOManiaApiEndpointsOrganizersHackathonTimelineCreateRequest,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
