/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createHackOManiaApiEndpointsParticipantsHackathonTeamsLeaveResponseFromDiscriminatorValue, type HackOManiaApiEndpointsParticipantsHackathonTeamsLeaveResponse } from '../../../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /participants/hackathons/{hackathonIdOrShortCode-id}/teams/leave
 */
export interface LeaveRequestBuilder extends BaseRequestBuilder<LeaveRequestBuilder> {
    /**
     * Removes the current user from their team. If they are the only member, the team will be deleted.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<HackOManiaApiEndpointsParticipantsHackathonTeamsLeaveResponse>}
     */
     post(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<HackOManiaApiEndpointsParticipantsHackathonTeamsLeaveResponse | undefined>;
    /**
     * Removes the current user from their team. If they are the only member, the team will be deleted.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const LeaveRequestBuilderUriTemplate = "{+baseurl}/participants/hackathons/{hackathonIdOrShortCode%2Did}/teams/leave";
/**
 * Metadata for all the requests in the request builder.
 */
export const LeaveRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: LeaveRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "send",
        responseBodyFactory:  createHackOManiaApiEndpointsParticipantsHackathonTeamsLeaveResponseFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
