/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createHackOManiaApiEndpointsParticipantsHackathonSubmissionsCreateResponseFromDiscriminatorValue, createHackOManiaApiEndpointsParticipantsHackathonSubmissionsListResponseFromDiscriminatorValue, serializeHackOManiaApiEndpointsParticipantsHackathonSubmissionsCreateRequest, serializeHackOManiaApiEndpointsParticipantsHackathonSubmissionsCreateResponse, type HackOManiaApiEndpointsParticipantsHackathonSubmissionsCreateRequest, type HackOManiaApiEndpointsParticipantsHackathonSubmissionsCreateResponse, type HackOManiaApiEndpointsParticipantsHackathonSubmissionsListResponse } from '../../../../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /participants/hackathons/{hackathonIdOrShortCode-id}/teams/{teamId}/submissions
 */
export interface SubmissionsRequestBuilder extends BaseRequestBuilder<SubmissionsRequestBuilder> {
    /**
     * Retrieves all submissions for a team in the hackathon.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<HackOManiaApiEndpointsParticipantsHackathonSubmissionsListResponse>}
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<HackOManiaApiEndpointsParticipantsHackathonSubmissionsListResponse | undefined>;
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<HackOManiaApiEndpointsParticipantsHackathonSubmissionsCreateResponse>}
     */
     post(body: HackOManiaApiEndpointsParticipantsHackathonSubmissionsCreateRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<HackOManiaApiEndpointsParticipantsHackathonSubmissionsCreateResponse | undefined>;
    /**
     * Retrieves all submissions for a team in the hackathon.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: HackOManiaApiEndpointsParticipantsHackathonSubmissionsCreateRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const SubmissionsRequestBuilderUriTemplate = "{+baseurl}/participants/hackathons/{hackathonIdOrShortCode%2Did}/teams/{teamId}/submissions";
/**
 * Metadata for all the requests in the request builder.
 */
export const SubmissionsRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: SubmissionsRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "send",
        responseBodyFactory:  createHackOManiaApiEndpointsParticipantsHackathonSubmissionsListResponseFromDiscriminatorValue,
    },
    post: {
        uriTemplate: SubmissionsRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "send",
        responseBodyFactory:  createHackOManiaApiEndpointsParticipantsHackathonSubmissionsCreateResponseFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeHackOManiaApiEndpointsParticipantsHackathonSubmissionsCreateRequest,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
