/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createHackOManiaApiEndpointsOrganizersHackathonJudgesGetResponseFromDiscriminatorValue, createHackOManiaApiEndpointsOrganizersHackathonJudgesUpdateResponseFromDiscriminatorValue, serializeHackOManiaApiEndpointsOrganizersHackathonJudgesUpdateRequest, serializeHackOManiaApiEndpointsOrganizersHackathonJudgesUpdateResponse, type HackOManiaApiEndpointsOrganizersHackathonJudgesGetResponse, type HackOManiaApiEndpointsOrganizersHackathonJudgesUpdateRequest, type HackOManiaApiEndpointsOrganizersHackathonJudgesUpdateResponse } from '../../../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /organizers/hackathons/{hackathonId}/judges/{judgeId}
 */
export interface WithJudgeItemRequestBuilder extends BaseRequestBuilder<WithJudgeItemRequestBuilder> {
    /**
     * Retrieves details about a specific judge including their secret.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<HackOManiaApiEndpointsOrganizersHackathonJudgesGetResponse>}
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<HackOManiaApiEndpointsOrganizersHackathonJudgesGetResponse | undefined>;
    /**
     * Updates judge details. Can regenerate the secret to invalidate old links.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<HackOManiaApiEndpointsOrganizersHackathonJudgesUpdateResponse>}
     */
     patch(body: HackOManiaApiEndpointsOrganizersHackathonJudgesUpdateRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<HackOManiaApiEndpointsOrganizersHackathonJudgesUpdateResponse | undefined>;
    /**
     * Retrieves details about a specific judge including their secret.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
    /**
     * Updates judge details. Can regenerate the secret to invalidate old links.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPatchRequestInformation(body: HackOManiaApiEndpointsOrganizersHackathonJudgesUpdateRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const WithJudgeItemRequestBuilderUriTemplate = "{+baseurl}/organizers/hackathons/{hackathonId}/judges/{judgeId}";
/**
 * Metadata for all the requests in the request builder.
 */
export const WithJudgeItemRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: WithJudgeItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "send",
        responseBodyFactory:  createHackOManiaApiEndpointsOrganizersHackathonJudgesGetResponseFromDiscriminatorValue,
    },
    patch: {
        uriTemplate: WithJudgeItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "send",
        responseBodyFactory:  createHackOManiaApiEndpointsOrganizersHackathonJudgesUpdateResponseFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeHackOManiaApiEndpointsOrganizersHackathonJudgesUpdateRequest,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
