/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { HackathonsRequestBuilderNavigationMetadata, HackathonsRequestBuilderRequestsMetadata, type HackathonsRequestBuilder } from './hackathons/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /organizers
 */
export interface OrganizersRequestBuilder extends BaseRequestBuilder<OrganizersRequestBuilder> {
    /**
     * The hackathons property
     */
    get hackathons(): HackathonsRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const OrganizersRequestBuilderUriTemplate = "{+baseurl}/organizers";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const OrganizersRequestBuilderNavigationMetadata: Record<Exclude<keyof OrganizersRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    hackathons: {
        requestsMetadata: HackathonsRequestBuilderRequestsMetadata,
        navigationMetadata: HackathonsRequestBuilderNavigationMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
