/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createHackOManiaApiEndpointsParticipantsHackathonResourcesListResponseFromDiscriminatorValue, type HackOManiaApiEndpointsParticipantsHackathonResourcesListResponse } from '../../../../models/index.js';
// @ts-ignore
import { type WithResourceItemRequestBuilder, WithResourceItemRequestBuilderNavigationMetadata } from './item/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /participants/hackathons/{id}/resources
 */
export interface ResourcesRequestBuilder extends BaseRequestBuilder<ResourcesRequestBuilder> {
    /**
     * Gets an item from the ApiSdk.participants.hackathons.item.resources.item collection
     * @param resourceId Unique identifier of the item
     * @returns {WithResourceItemRequestBuilder}
     */
     byResourceId(resourceId: string) : WithResourceItemRequestBuilder;
    /**
     * Retrieves all resources available for a hackathon.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<HackOManiaApiEndpointsParticipantsHackathonResourcesListResponse>}
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<HackOManiaApiEndpointsParticipantsHackathonResourcesListResponse | undefined>;
    /**
     * Retrieves all resources available for a hackathon.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const ResourcesRequestBuilderUriTemplate = "{+baseurl}/participants/hackathons/{id}/resources";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const ResourcesRequestBuilderNavigationMetadata: Record<Exclude<keyof ResourcesRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byResourceId: {
        navigationMetadata: WithResourceItemRequestBuilderNavigationMetadata,
        pathParametersMappings: ["resourceId"],
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const ResourcesRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: ResourcesRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "send",
        responseBodyFactory:  createHackOManiaApiEndpointsParticipantsHackathonResourcesListResponseFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
