/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createHackOManiaApiEndpointsOrganizersHackathonResourcesStatisticsResponseFromDiscriminatorValue, type HackOManiaApiEndpointsOrganizersHackathonResourcesStatisticsResponse } from '../../../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /organizers/hackathons/{hackathonId}/resources/statistics
 */
export interface StatisticsRequestBuilder extends BaseRequestBuilder<StatisticsRequestBuilder> {
    /**
     * Returns redemption statistics for all resources or a selected resource, including team-grouped participant breakdowns.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<HackOManiaApiEndpointsOrganizersHackathonResourcesStatisticsResponse>}
     */
     get(requestConfiguration?: RequestConfiguration<StatisticsRequestBuilderGetQueryParameters> | undefined) : Promise<HackOManiaApiEndpointsOrganizersHackathonResourcesStatisticsResponse | undefined>;
    /**
     * Returns redemption statistics for all resources or a selected resource, including team-grouped participant breakdowns.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<StatisticsRequestBuilderGetQueryParameters> | undefined) : RequestInformation;
}
/**
 * Returns redemption statistics for all resources or a selected resource, including team-grouped participant breakdowns.
 */
export interface StatisticsRequestBuilderGetQueryParameters {
    resourceId?: string;
}
/**
 * Uri template for the request builder.
 */
export const StatisticsRequestBuilderUriTemplate = "{+baseurl}/organizers/hackathons/{hackathonId}/resources/statistics{?resourceId*}";
/**
 * Metadata for all the requests in the request builder.
 */
export const StatisticsRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: StatisticsRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "send",
        responseBodyFactory:  createHackOManiaApiEndpointsOrganizersHackathonResourcesStatisticsResponseFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
