/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createHackOManiaApiEndpointsOrganizersHackathonRegistrationQuestionsUpdateResponseFromDiscriminatorValue, serializeHackOManiaApiEndpointsOrganizersHackathonRegistrationQuestionsUpdateRequest, serializeHackOManiaApiEndpointsOrganizersHackathonRegistrationQuestionsUpdateResponse, type HackOManiaApiEndpointsOrganizersHackathonRegistrationQuestionsUpdateRequest, type HackOManiaApiEndpointsOrganizersHackathonRegistrationQuestionsUpdateResponse } from '../../../../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /organizers/hackathons/{hackathonId}/registration/questions/{questionId}
 */
export interface WithQuestionItemRequestBuilder extends BaseRequestBuilder<WithQuestionItemRequestBuilder> {
    /**
     * Delete a registration question and all its options. This will also delete any participant submissions for this question.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     */
     delete(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<void>;
    /**
     * Update an existing registration question and its options.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<HackOManiaApiEndpointsOrganizersHackathonRegistrationQuestionsUpdateResponse>}
     */
     patch(body: HackOManiaApiEndpointsOrganizersHackathonRegistrationQuestionsUpdateRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<HackOManiaApiEndpointsOrganizersHackathonRegistrationQuestionsUpdateResponse | undefined>;
    /**
     * Delete a registration question and all its options. This will also delete any participant submissions for this question.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toDeleteRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
    /**
     * Update an existing registration question and its options.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPatchRequestInformation(body: HackOManiaApiEndpointsOrganizersHackathonRegistrationQuestionsUpdateRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const WithQuestionItemRequestBuilderUriTemplate = "{+baseurl}/organizers/hackathons/{hackathonId}/registration/questions/{questionId}";
/**
 * Metadata for all the requests in the request builder.
 */
export const WithQuestionItemRequestBuilderRequestsMetadata: RequestsMetadata = {
    delete: {
        uriTemplate: WithQuestionItemRequestBuilderUriTemplate,
        adapterMethodName: "sendNoResponseContent",
    },
    patch: {
        uriTemplate: WithQuestionItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "send",
        responseBodyFactory:  createHackOManiaApiEndpointsOrganizersHackathonRegistrationQuestionsUpdateResponseFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeHackOManiaApiEndpointsOrganizersHackathonRegistrationQuestionsUpdateRequest,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
