/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createHackOManiaApiEndpointsAdminCachePurgeResponseFromDiscriminatorValue, type HackOManiaApiEndpointsAdminCachePurgeResponse } from '../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /admin/cache/purge
 */
export interface PurgeRequestBuilder extends BaseRequestBuilder<PurgeRequestBuilder> {
    /**
     * Clears the in-process SqlSugar data cache used by the API server.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<HackOManiaApiEndpointsAdminCachePurgeResponse>}
     */
     post(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<HackOManiaApiEndpointsAdminCachePurgeResponse | undefined>;
    /**
     * Clears the in-process SqlSugar data cache used by the API server.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const PurgeRequestBuilderUriTemplate = "{+baseurl}/admin/cache/purge";
/**
 * Metadata for all the requests in the request builder.
 */
export const PurgeRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: PurgeRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "send",
        responseBodyFactory:  createHackOManiaApiEndpointsAdminCachePurgeResponseFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
