/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createFastEndpointsErrorResponseFromDiscriminatorValue, createHackOManiaApiEndpointsOrganizersHackathonParticipantsGetResponseFromDiscriminatorValue, type FastEndpointsErrorResponse, type HackOManiaApiEndpointsOrganizersHackathonParticipantsGetResponse } from '../../../../../models/index.js';
// @ts-ignore
import { ResourcesRequestBuilderNavigationMetadata, type ResourcesRequestBuilder } from './resources/index.js';
// @ts-ignore
import { ReviewRequestBuilderRequestsMetadata, type ReviewRequestBuilder } from './review/index.js';
// @ts-ignore
import { type VenueRequestBuilder, VenueRequestBuilderNavigationMetadata } from './venue/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /organizers/hackathons/{hackathonId}/participants/{participantUser-id}
 */
export interface ParticipantUserItemRequestBuilder extends BaseRequestBuilder<ParticipantUserItemRequestBuilder> {
    /**
     * The resources property
     */
    get resources(): ResourcesRequestBuilder;
    /**
     * The review property
     */
    get review(): ReviewRequestBuilder;
    /**
     * The venue property
     */
    get venue(): VenueRequestBuilder;
    /**
     * Retrieves full details for a participant, including registration responses.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<HackOManiaApiEndpointsOrganizersHackathonParticipantsGetResponse>}
     * @throws {FastEndpointsErrorResponse} error when the service returns a 400 status code
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<HackOManiaApiEndpointsOrganizersHackathonParticipantsGetResponse | undefined>;
    /**
     * Retrieves full details for a participant, including registration responses.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const ParticipantUserItemRequestBuilderUriTemplate = "{+baseurl}/organizers/hackathons/{hackathonId}/participants/{participantUser%2Did}";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const ParticipantUserItemRequestBuilderNavigationMetadata: Record<Exclude<keyof ParticipantUserItemRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    resources: {
        navigationMetadata: ResourcesRequestBuilderNavigationMetadata,
    },
    review: {
        requestsMetadata: ReviewRequestBuilderRequestsMetadata,
    },
    venue: {
        navigationMetadata: VenueRequestBuilderNavigationMetadata,
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const ParticipantUserItemRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: ParticipantUserItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createFastEndpointsErrorResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createHackOManiaApiEndpointsOrganizersHackathonParticipantsGetResponseFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
