/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { ReviewRequestBuilderRequestsMetadata, type ReviewRequestBuilder } from './review/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /organizers/hackathons/{hackathonId}/participants/{participantUserId}
 */
export interface WithParticipantUserItemRequestBuilder extends BaseRequestBuilder<WithParticipantUserItemRequestBuilder> {
    /**
     * The review property
     */
    get review(): ReviewRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const WithParticipantUserItemRequestBuilderUriTemplate = "{+baseurl}/organizers/hackathons/{hackathonId}/participants/{participantUserId}";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const WithParticipantUserItemRequestBuilderNavigationMetadata: Record<Exclude<keyof WithParticipantUserItemRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    review: {
        requestsMetadata: ReviewRequestBuilderRequestsMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
