/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createHackOManiaApiEndpointsParticipantsTeamsJoinByCodeResponseFromDiscriminatorValue, serializeHackOManiaApiEndpointsParticipantsTeamsJoinByCodeRequest, serializeHackOManiaApiEndpointsParticipantsTeamsJoinByCodeResponse, type HackOManiaApiEndpointsParticipantsTeamsJoinByCodeRequest, type HackOManiaApiEndpointsParticipantsTeamsJoinByCodeResponse } from '../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /participants/teams/join
 */
export interface JoinRequestBuilder extends BaseRequestBuilder<JoinRequestBuilder> {
    /**
     * Joins the current user to a team using only the team's join code. If the user is not already a participant in the hackathon, they will be automatically registered.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<HackOManiaApiEndpointsParticipantsTeamsJoinByCodeResponse>}
     */
     post(body: HackOManiaApiEndpointsParticipantsTeamsJoinByCodeRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<HackOManiaApiEndpointsParticipantsTeamsJoinByCodeResponse | undefined>;
    /**
     * Joins the current user to a team using only the team's join code. If the user is not already a participant in the hackathon, they will be automatically registered.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: HackOManiaApiEndpointsParticipantsTeamsJoinByCodeRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const JoinRequestBuilderUriTemplate = "{+baseurl}/participants/teams/join";
/**
 * Metadata for all the requests in the request builder.
 */
export const JoinRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: JoinRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "send",
        responseBodyFactory:  createHackOManiaApiEndpointsParticipantsTeamsJoinByCodeResponseFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeHackOManiaApiEndpointsParticipantsTeamsJoinByCodeRequest,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
