/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createHackOManiaApiEndpointsParticipantsHackathonGetResponseFromDiscriminatorValue, type HackOManiaApiEndpointsParticipantsHackathonGetResponse } from '../../../models/index.js';
// @ts-ignore
import { ChallengesRequestBuilderNavigationMetadata, ChallengesRequestBuilderRequestsMetadata, type ChallengesRequestBuilder } from './challenges/index.js';
// @ts-ignore
import { JoinRequestBuilderRequestsMetadata, type JoinRequestBuilder } from './join/index.js';
// @ts-ignore
import { RegistrationRequestBuilderNavigationMetadata, type RegistrationRequestBuilder } from './registration/index.js';
// @ts-ignore
import { ResourcesRequestBuilderRequestsMetadata, type ResourcesRequestBuilder } from './resources/index.js';
// @ts-ignore
import { StatusRequestBuilderRequestsMetadata, type StatusRequestBuilder } from './status/index.js';
// @ts-ignore
import { SubmissionsRequestBuilderNavigationMetadata, type SubmissionsRequestBuilder } from './submissions/index.js';
// @ts-ignore
import { TeamsRequestBuilderNavigationMetadata, TeamsRequestBuilderRequestsMetadata, type TeamsRequestBuilder } from './teams/index.js';
// @ts-ignore
import { type VenueRequestBuilder, VenueRequestBuilderNavigationMetadata } from './venue/index.js';
// @ts-ignore
import { type WorkshopsRequestBuilder, WorkshopsRequestBuilderNavigationMetadata, WorkshopsRequestBuilderRequestsMetadata } from './workshops/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /participants/hackathons/{hackathonIdOrShortCode-id}
 */
export interface HackathonIdOrShortCodeItemRequestBuilder extends BaseRequestBuilder<HackathonIdOrShortCodeItemRequestBuilder> {
    /**
     * The challenges property
     */
    get challenges(): ChallengesRequestBuilder;
    /**
     * The join property
     */
    get join(): JoinRequestBuilder;
    /**
     * The registration property
     */
    get registration(): RegistrationRequestBuilder;
    /**
     * The resources property
     */
    get resources(): ResourcesRequestBuilder;
    /**
     * The status property
     */
    get status(): StatusRequestBuilder;
    /**
     * The submissions property
     */
    get submissions(): SubmissionsRequestBuilder;
    /**
     * The teams property
     */
    get teams(): TeamsRequestBuilder;
    /**
     * The venue property
     */
    get venue(): VenueRequestBuilder;
    /**
     * The workshops property
     */
    get workshops(): WorkshopsRequestBuilder;
    /**
     * Retrieves public details about a hackathon by ID or short code.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<HackOManiaApiEndpointsParticipantsHackathonGetResponse>}
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<HackOManiaApiEndpointsParticipantsHackathonGetResponse | undefined>;
    /**
     * Retrieves public details about a hackathon by ID or short code.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const HackathonIdOrShortCodeItemRequestBuilderUriTemplate = "{+baseurl}/participants/hackathons/{hackathonIdOrShortCode%2Did}";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const HackathonIdOrShortCodeItemRequestBuilderNavigationMetadata: Record<Exclude<keyof HackathonIdOrShortCodeItemRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    challenges: {
        requestsMetadata: ChallengesRequestBuilderRequestsMetadata,
        navigationMetadata: ChallengesRequestBuilderNavigationMetadata,
    },
    join: {
        requestsMetadata: JoinRequestBuilderRequestsMetadata,
    },
    registration: {
        navigationMetadata: RegistrationRequestBuilderNavigationMetadata,
    },
    resources: {
        requestsMetadata: ResourcesRequestBuilderRequestsMetadata,
    },
    status: {
        requestsMetadata: StatusRequestBuilderRequestsMetadata,
    },
    submissions: {
        navigationMetadata: SubmissionsRequestBuilderNavigationMetadata,
    },
    teams: {
        requestsMetadata: TeamsRequestBuilderRequestsMetadata,
        navigationMetadata: TeamsRequestBuilderNavigationMetadata,
    },
    venue: {
        navigationMetadata: VenueRequestBuilderNavigationMetadata,
    },
    workshops: {
        requestsMetadata: WorkshopsRequestBuilderRequestsMetadata,
        navigationMetadata: WorkshopsRequestBuilderNavigationMetadata,
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const HackathonIdOrShortCodeItemRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: HackathonIdOrShortCodeItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "send",
        responseBodyFactory:  createHackOManiaApiEndpointsParticipantsHackathonGetResponseFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
