name: Deploy (Infra)

on:
  push:
    paths:
      - "GeeksHackingPortal.Infra/**"
      - ".github/workflows/deploy-infra.yml"
    branches: ["main"]

jobs:
  build:
    concurrency: deploy
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10.0.x

      - uses: google-github-actions/auth@v3
        with:
          workload_identity_provider: projects/242247218750/locations/global/workloadIdentityPools/github/providers/github
          service_account: pulumi-deployer@hackomania-event-portal.iam.gserviceaccount.com

      - uses: pulumi/actions@v6
        env:
          PULUMI_CONFIG_PASSPHRASE: ""
        with:
          command: up
          refresh: true
          stack-name: production
          cloud-url: gs://hackomania-pulumi-state
          work-dir: GeeksHackingPortal.Infra
