/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createHackOManiaApiEndpointsOrganizersHackathonGetResponseFromDiscriminatorValue, createHackOManiaApiEndpointsOrganizersHackathonUpdateResponseFromDiscriminatorValue, serializeHackOManiaApiEndpointsOrganizersHackathonUpdateRequest, serializeHackOManiaApiEndpointsOrganizersHackathonUpdateResponse, type HackOManiaApiEndpointsOrganizersHackathonGetResponse, type HackOManiaApiEndpointsOrganizersHackathonUpdateRequest, type HackOManiaApiEndpointsOrganizersHackathonUpdateResponse } from '../../../models/index.js';
// @ts-ignore
import { ChallengesRequestBuilderNavigationMetadata, ChallengesRequestBuilderRequestsMetadata, type ChallengesRequestBuilder } from './challenges/index.js';
// @ts-ignore
import { JudgesRequestBuilderNavigationMetadata, JudgesRequestBuilderRequestsMetadata, type JudgesRequestBuilder } from './judges/index.js';
// @ts-ignore
import { OrganizersRequestBuilderNavigationMetadata, OrganizersRequestBuilderRequestsMetadata, type OrganizersRequestBuilder } from './organizers/index.js';
// @ts-ignore
import { ParticipantsRequestBuilderNavigationMetadata, ParticipantsRequestBuilderRequestsMetadata, type ParticipantsRequestBuilder } from './participants/index.js';
// @ts-ignore
import { RegistrationRequestBuilderNavigationMetadata, type RegistrationRequestBuilder } from './registration/index.js';
// @ts-ignore
import { ResourcesRequestBuilderNavigationMetadata, ResourcesRequestBuilderRequestsMetadata, type ResourcesRequestBuilder } from './resources/index.js';
// @ts-ignore
import { SubmissionsRequestBuilderNavigationMetadata, SubmissionsRequestBuilderRequestsMetadata, type SubmissionsRequestBuilder } from './submissions/index.js';
// @ts-ignore
import { TeamsRequestBuilderRequestsMetadata, type TeamsRequestBuilder } from './teams/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /organizers/hackathons/{hackathonId}
 */
export interface WithHackathonItemRequestBuilder extends BaseRequestBuilder<WithHackathonItemRequestBuilder> {
    /**
     * The challenges property
     */
    get challenges(): ChallengesRequestBuilder;
    /**
     * The judges property
     */
    get judges(): JudgesRequestBuilder;
    /**
     * The organizers property
     */
    get organizers(): OrganizersRequestBuilder;
    /**
     * The participants property
     */
    get participants(): ParticipantsRequestBuilder;
    /**
     * The registration property
     */
    get registration(): RegistrationRequestBuilder;
    /**
     * The resources property
     */
    get resources(): ResourcesRequestBuilder;
    /**
     * The submissions property
     */
    get submissions(): SubmissionsRequestBuilder;
    /**
     * The teams property
     */
    get teams(): TeamsRequestBuilder;
    /**
     * Retrieves detailed information about a specific hackathon.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<HackOManiaApiEndpointsOrganizersHackathonGetResponse>}
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<HackOManiaApiEndpointsOrganizersHackathonGetResponse | undefined>;
    /**
     * Updates the hackathon information.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<HackOManiaApiEndpointsOrganizersHackathonUpdateResponse>}
     */
     patch(body: HackOManiaApiEndpointsOrganizersHackathonUpdateRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<HackOManiaApiEndpointsOrganizersHackathonUpdateResponse | undefined>;
    /**
     * Retrieves detailed information about a specific hackathon.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
    /**
     * Updates the hackathon information.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPatchRequestInformation(body: HackOManiaApiEndpointsOrganizersHackathonUpdateRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const WithHackathonItemRequestBuilderUriTemplate = "{+baseurl}/organizers/hackathons/{hackathonId}";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const WithHackathonItemRequestBuilderNavigationMetadata: Record<Exclude<keyof WithHackathonItemRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    challenges: {
        requestsMetadata: ChallengesRequestBuilderRequestsMetadata,
        navigationMetadata: ChallengesRequestBuilderNavigationMetadata,
    },
    judges: {
        requestsMetadata: JudgesRequestBuilderRequestsMetadata,
        navigationMetadata: JudgesRequestBuilderNavigationMetadata,
    },
    organizers: {
        requestsMetadata: OrganizersRequestBuilderRequestsMetadata,
        navigationMetadata: OrganizersRequestBuilderNavigationMetadata,
    },
    participants: {
        requestsMetadata: ParticipantsRequestBuilderRequestsMetadata,
        navigationMetadata: ParticipantsRequestBuilderNavigationMetadata,
    },
    registration: {
        navigationMetadata: RegistrationRequestBuilderNavigationMetadata,
    },
    resources: {
        requestsMetadata: ResourcesRequestBuilderRequestsMetadata,
        navigationMetadata: ResourcesRequestBuilderNavigationMetadata,
    },
    submissions: {
        requestsMetadata: SubmissionsRequestBuilderRequestsMetadata,
        navigationMetadata: SubmissionsRequestBuilderNavigationMetadata,
    },
    teams: {
        requestsMetadata: TeamsRequestBuilderRequestsMetadata,
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const WithHackathonItemRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: WithHackathonItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "send",
        responseBodyFactory:  createHackOManiaApiEndpointsOrganizersHackathonGetResponseFromDiscriminatorValue,
    },
    patch: {
        uriTemplate: WithHackathonItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "send",
        responseBodyFactory:  createHackOManiaApiEndpointsOrganizersHackathonUpdateResponseFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeHackOManiaApiEndpointsOrganizersHackathonUpdateRequest,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
